force-app/main/default/objects/Partner_Tier__c/Partner_Tier__c.object-meta.xml
<CustomObject>
    <label>Partner Tier</label>
    <nameField>
        <label>Partner Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Tier__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Tiers</relationshipLabel>
    <relationshipName>Partner_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold Plus</fullName>
                <isActive>false</isActive>
                <label>Gold Plus</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier_End_Date__c</fullName>
    <label>Partner Tier End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/PartnerTier_Status__c.field-meta.xml
<CustomField>
    <fullName>PartnerTier_Status__c</fullName>
    <label>Partner Tier Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerTierTriggerHandler.cls
public class PartnerTierTriggerHandler {
    
    public static void beforePartnerTier(List<Partner_Tier__c> newList){
        Set<Id> partnerIdSet = new Set<Id>();
        Set<Id>	partnertoUpdateSet = new Set<Id>();
        Set<ID> existingPTSet = new Set<ID>();
        String errorMessage = System.Label.PartnerTier_ErrorMessage;
        
            for(Partner_Tier__c pt: newList){
                    partnerIdSet.add(pt.Partner__c);
            }
        
        
            List<Partner_Tier__c> existingPTList = [Select ID,Name,PartnerTier_Status__c From Partner_Tier__c Where PartnerTier_Status__c = 'Active' AND Partner__c IN: partnerIdSet];    
        for(Partner_Tier__c existingpt:existingPTList){
            existingPTSet.add(existingpt.ID);
        }
        	for(Partner_Tier__c pt: newList){
                    if(existingPTList != null && existingPTList.size() > 0 && pt.PartnerTier_Status__c == 'Active' && !existingPTSet.contains(pt.ID)){
                        pt.addError(errorMessage); 
                    }
            }
    }
    
    public static void afterPartnerTier(Map<Id,Partner_Tier__c> newpartnerTierMap,Map<Id,Partner_Tier__c> oldpartnerTierMap){
        Set<Id> partnerIdSet = new Set<Id>();
        Set<Id>	partnertoUpdateSet = new Set<Id>();
        String errorMessage = System.Label.PartnerTier_ErrorMessage;
        for(Partner_Tier__c pt: newpartnerTierMap.values()){
            //if(pt.Partner_Tier_End_Date__c == null || (pt.Partner_Tier_End_Date__c != null && pt.Partner_Tier_End_Date__c > Date.Today())){
                partnerIdSet.add(pt.Partner__c);
            //}
        }
        
        
            List<Partner_Tier__c> existingPTList = [Select ID,Name,PartnerTier_Status__c From Partner_Tier__c Where PartnerTier_Status__c = 'Active' AND Partner__c IN: partnerIdSet];
            for(Partner_Tier__c pt: newpartnerTierMap.values()){
                //if(pt.PartnerTier_Status__c != oldpartnerTierMap.get(pt.Id).PartnerTier_Status__c){
                if(existingPTList == null || existingPTList.size() == 0){
                    partnertoUpdateSet.add(pt.Partner__c);
                }  
            }
        
        if(partnertoUpdateSet != null && partnertoUpdateSet.size() > 0){
            PartnerMarginService.updatePartnerForInactiveTiers(partnertoUpdateSet); 
        }
    }
}