force-app/main/default/objects/OpportunityLineItem/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Opportunity.Partner__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Partner_Payment_OP_Bill_through__c.field-meta.xml
<CustomField>
    <fullName>Partner_Payment_OP_Bill_through__c</fullName>
    <label>Partner Payment % (Opp Product - BtP)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Partner_Payment_OppProduct__c.field-meta.xml
<CustomField>
    <fullName>Partner_Payment_OppProduct__c</fullName>
    <formula>IF( Partner_Payment_Opp_Product_Bill_thro__c &gt; 0, Partner_Payment_Opp_Product_Bill_thro__c , IF( Partner_Payment_OP_Direct__c &gt; 0 , Partner_Payment_OP_Direct__c , 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Payment (Opp Product)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/Partner_Client_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner-Client Relationship</label>
    <nameField>
        <label>Partner-Client Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner-Client Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships</relationshipLabel>
    <relationshipName>Partner_Client_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Client_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/Partner_Margin__c.object-meta.xml
<CustomObject>
    <label>Partner Margin</label>
    <nameField>
        <label>Partner Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Enhancement_Partner_Margin_Y1__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Partner_Margin_Y1__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>Enhancement - Partner Margin % (Y1)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins (Partner)</relationshipLabel>
    <relationshipName>Partner_Margins2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Billing_Type__c</fullName>
    <label>Partner Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill through Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold Plus</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Software_Partner_Margin_Y1__c.field-meta.xml
<CustomField>
    <fullName>Software_Partner_Margin_Y1__c</fullName>
    <label>Software - Partner Margin % (Y1)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/Partner_Margin_Product__c.object-meta.xml
<CustomObject>
    <label>Partner Margin Product</label>
    <nameField>
        <label>Partner Margin Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margin Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Partner Margin Products</relationshipLabel>
    <relationshipName>Partner_Margin_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Partner_Margin__c.field-meta.xml
<CustomField>
    <fullName>Partner_Margin__c</fullName>
    <label>Partner Margin</label>
    <referenceTo>Partner_Margin__c</referenceTo>
    <relationshipLabel>Partner Margin Products</relationshipLabel>
    <relationshipName>Partner_Margin_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Total_Price_Original__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Original__c</fullName>
    <label>Total Price (Original)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/Partner_Tier__c.object-meta.xml
<CustomObject>
    <label>Partner Tier</label>
    <nameField>
        <label>Partner Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Tier__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Tiers</relationshipLabel>
    <relationshipName>Partner_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold Plus</fullName>
                <isActive>false</isActive>
                <label>Gold Plus</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier_Margin__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier_Margin__c</fullName>
    <formula>IF( ISPICKVAL( Partner_Tier__c , &apos;Gold&apos;) , 0.3, IF(ISPICKVAL( Partner_Tier__c , &apos;Silver&apos;) , 0.2,IF(ISPICKVAL( Partner_Tier__c , &apos;Bronze&apos;) , 0.1,IF(ISPICKVAL( Partner_Tier__c , &apos;Gold Plus&apos;) , 0.3,0))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Tier Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/PartnerTier_Status__c.field-meta.xml
<CustomField>
    <fullName>PartnerTier_Status__c</fullName>
    <label>Partner Tier Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerMarginTriggerHandler.cls
public class PartnerMarginTriggerHandler {
    
    public static void afterTrigger(Map<Id,Partner_Margin__c> newMap,Map<Id,Partner_Margin__c> oldMap){
        Set<Id> oppIdSet = new Set<Id>();
        Set<Id> oppProductIdSet = new Set<Id>();
        Set<Id> pmIdSet = new Set<Id>();
        String PMStatusBtP = System.Label.PM_Status_BillThroughPartner;
        String PMStatusDirect = System.Label.PM_Status_Direct;
        //List<Partner_Margin__c> pmListToUpdate = new List<Partner_Margin__c>();
        //Map<ID,Partner_Tier__c> partnerIdToPartnerTierMap = new Map<ID,Partner_Tier__c>();
        for(Partner_Margin__c pm: newMap.values()){
            if(pm.Software_Partner_Margin_Y1__c != oldMap.get(pm.Id).Software_Partner_Margin_Y1__c || pm.Enhancement_Partner_Margin_Y1__c != oldMap.get(pm.Id).Enhancement_Partner_Margin_Y1__c || pm.Partner__c != oldMap.get(pm.Id).Partner__c || (pm.Partner_Billing_Type__c != oldMap.get(pm.Id).Partner_Billing_Type__c && (pm.Partner_Billing_Type__c == PMStatusDirect || oldMap.get(pm.Id).Partner_Billing_Type__c == PMStatusDirect))){
                oppIdSet.add(pm.Opportunity__c);
                pmIdSet.add(pm.Id);
            }
            if(pm.Partner_Billing_Type__c != oldMap.get(pm.Id).Partner_Billing_Type__c && pm.Partner_Billing_Type__c == PMStatusBtP){
                pmIdSet.add(pm.Id);   
            }
        }
        
        Map<Id,OpportunityLineItem> oppProductMap = new Map<Id,OpportunityLineItem>([Select ID,Name From OpportunityLineItem where OpportunityId In :oppIdSet]);
        try{
            
            if(oppIdSet != null && oppIdSet.size() > 0){
                updateRelatedOppProducts(oppIdSet);
                if(!System.isFuture()){
                    CouponService.updateOppProductCoupons(oppProductMap.keySet());
                }
            }
            if(pmIdSet != null && pmIdSet.size() > 0){
                updateRelatedPMProducts(pmIdSet);
            }
            
        }catch(Exception exp){
            System.debug('Exception: '+exp.getMessage());
        }
        
    }
    
    public static void beforeDelete(List<Partner_Margin__c> oldPmList){
        Set<Id> oppIdSet = new Set<Id>();
        for(Partner_Margin__c pm: oldPmList){
            oppIdSet.add(pm.Opportunity__c);
        }
        if(oppIdSet != null && oppIdSet.size() > 0){
            updateRelatedOppProducts(oppIdSet); 
        }
    }
    
    public static void updateRelatedOppProducts(Set<Id> oppIdSet){
        if(oppIdSet != null && oppIdSet.size() > 0){
            Map<Id,OpportunityLineItem> oppProductMap = new Map<Id,OpportunityLineItem>([Select ID from OpportunityLineItem where OpportunityId In: oppIdSet]);
            if(oppProductMap != null && oppProductMap.size() > 0){
                PartnerMarginService.updateOppProductWithPM(oppProductMap.keySet()); 
            }
        }
    }
    
    @future
    public static void updateRelatedPMProducts(Set<Id> pmIdSet){
        List<Partner_Margin_Product__c> pmProductList = new List<Partner_Margin_Product__c>();
        Set<Id> oppProductIdSet = new Set<Id>();
        Map<Id,Decimal> BtPMap = new Map<Id,Decimal>();
        String PMStatusBtP = System.Label.PM_Status_BillThroughPartner;
        String PMStatusDirect = System.Label.PM_Status_Direct;
        if(pmIdSet != null && pmIdSet.size() > 0){
            pmProductList = [
                SELECT 
                    Id,Opportunity_Product__r.TotalPrice,Total_Price_Original__c,Opportunity_Product__c,Opportunity_Product__r.Partner_Payment_OppProduct__c,
                    Partner_Margin__r.Partner_Billing_Type__c,Opportunity_Product__r.Partner_Payment_OP_Bill_through__c 
                FROM Partner_Margin_Product__c 
                WHERE Partner_Margin__c 
                IN: pmIdSet 
                AND Opportunity_Product__c != null
            ];
            for(Partner_Margin_Product__c pmProduct : pmProductList){
                if(pmProduct.Opportunity_Product__r.Partner_Payment_OP_Bill_through__c == null){                   
                    BtPMap.put(pmProduct.Id,0.00);
                } else {
                    BtPMap.put(pmProduct.Id,pmProduct.Opportunity_Product__r.Partner_Payment_OP_Bill_through__c);
                }
            }
            
            if(pmProductList != null && pmProductList.size() > 0){
                for(Partner_Margin_Product__c pmProduct : pmProductList){
                    if(pmProduct.Partner_Margin__r.Partner_Billing_Type__c == PMStatusDirect){
                        pmProduct.Total_Price_Original__c =  pmProduct.Opportunity_Product__r.TotalPrice; 
                    } else if (pmProduct.Partner_Margin__r.Partner_Billing_Type__c == PMStatusBtP){
                        pmProduct.Total_Price_Original__c = pmProduct.Opportunity_Product__r.TotalPrice + pmProduct.Opportunity_Product__r.Partner_Payment_OppProduct__c; 
                    }
                    
                }
                update pmProductList;                
            }
        }
    }
    
    public static void beforeUpdate(Map<Id,Partner_Margin__c> newMap,Map<Id,Partner_Margin__c> oldMap){
        Set<ID> partnerIdSet = new Set<ID>();
        Map<ID,Partner_Tier__c> partnerIdToPartnerTierMap = new Map<ID,Partner_Tier__c>();
        Map<String,Partner_Client_Relationship__c> partnerIdToPartnerClientRelMap = new Map<String,Partner_Client_Relationship__c>();
        
        for(Partner_Margin__c pm: newMap.values()){
            partnerIdSet.add(pm.Partner__c); 
        }
        for(Partner_Tier__c partnerTier :[SELECT Id, Partner_Tier_Margin__c, Partner__c,Partner_Tier__c FROM Partner_Tier__c WHERE 
                                         PartnerTier_Status__c = 'Active' AND Partner__c In: partnerIdSet]){
                                             partnerIdToPartnerTierMap.put(partnerTier.Partner__c,partnerTier);    
                                         }
        for(Partner_Client_Relationship__c partnerClientRelp:[Select ID,Partner__c,Client__c,Partner_Client_Margin_Eligibility__c from Partner_Client_Relationship__c where 
                                                              Partner__c In: partnerIdSet]){
                                                                  String partnerClientKey = (String)partnerClientRelp.Partner__c+(String)partnerClientRelp.Client__c;
                                                                  partnerIdToPartnerClientRelMap.put(partnerClientKey,partnerClientRelp);    
                                                              }
        for(Partner_Margin__c pm: newMap.values()){
            
            if(pm.Partner__c != oldMap.get(pm.Id).Partner__c){
                if(partnerIdToPartnerTierMap != null && partnerIdToPartnerTierMap.size()>0){
                    pm.Software_Partner_Margin_Y1__c = partnerIdToPartnerTierMap.get(pm.Partner__c).Partner_Tier_Margin__c;
                    pm.Partner_Tier__c = partnerIdToPartnerTierMap.get(pm.Partner__c).Partner_Tier__c;
                    if(partnerIdToPartnerTierMap.get(pm.Partner__c).Partner_Tier__c == 'Bronze'){
                        pm.Enhancement_Partner_Margin_Y1__c = partnerIdToPartnerTierMap.get(pm.Partner__c).Partner_Tier_Margin__c;  
                    }else{
                        pm.Enhancement_Partner_Margin_Y1__c = 15;
                    }
                }else{
                    pm.addError(System.Label.PM_MissingPartnerTierMessage);
                }
                
                if(partnerIdToPartnerClientRelMap != null && partnerIdToPartnerClientRelMap.size()>0){
                    String pmClientKey = (String)pm.Partner__c + (String)pm.Client__c;
                    pm.Partner_Client_Margin_Eligibility__c = partnerIdToPartnerClientRelMap.get(pmClientKey).Partner_Client_Margin_Eligibility__c;
                }
            }
        }
    }
}