force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Reseller_Partner.recordType-meta.xml
<RecordType>
    <fullName>Reseller_Partner</fullName>
    <active>true</active>
    <label>Reseller Partner</label>
</RecordType>

force-app/main/default/objects/Partner_Margin__c/Partner_Margin__c.object-meta.xml
<CustomObject>
    <label>Partner Margin</label>
    <nameField>
        <label>Partner Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins (Partner)</relationshipLabel>
    <relationshipName>Partner_Margins2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdatePartnerJob.cls
global class UpdatePartnerJob implements Schedulable,Database.Batchable<sObject> {
global Database.QueryLocator start(Database.BatchableContext BC) {
    
    //To Run Monthly
    RecordType acctPartnerResellerRecordType = [Select ID,DeveloperName From RecordType where DeveloperName='Reseller_Partner' limit 1];
    ID recordType = acctPartnerResellerRecordType.Id;
    String query = 'Select ID,Name,(Select ID,Name From Partner_Margins2__r) From Account where RecordTypeId=:recordType Limit 200';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> partnerList) {
        Map<Id,Partner_Margin__c> partnerPMMap = new Map<Id,Partner_Margin__c>();
        try{
            for(Account partner:partnerList){
                for(Partner_Margin__c pm: partner.Partner_Margins2__r){
                    partnerPMMap.put(partner.Id,pm);
                } 
            }
            
            update partnerPMMap.values();
            
        }catch(Exception e) {
            System.debug(e.getMessage());
        }    
    }
    
    global void execute(SchedulableContext sc) {
        UpdatePartnerJob b = new UpdatePartnerJob(); 
        Database.executeBatch(b);
    }
    
    
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }

}