force-app/main/default/objects/Account/fields/ABR_Happened__c.field-meta.xml
<CustomField>
    <fullName>ABR_Happened__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ABR Happened</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABR_Happened_Set__c.field-meta.xml
<CustomField>
    <fullName>ABR_Happened_Set__c</fullName>
    <description>Timestamp of when ABR Happened was first set to true</description>
    <label>ABR Happened Set</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABR_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>ABR_Scheduled_Date__c</fullName>
    <label>ABR Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABR_Scheduled_Date_Set__c.field-meta.xml
<CustomField>
    <fullName>ABR_Scheduled_Date_Set__c</fullName>
    <description>Timestamp of when ABR Scheduled Date was first populated</description>
    <label>ABR Scheduled Date Set</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Class__c.field-meta.xml
<CustomField>
    <fullName>Customer_Class__c</fullName>
    <inlineHelpText>Original customer class - taken from ERP</inlineHelpText>
    <label>Customer Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End User Cloud</fullName>
            </value>
            <value>
                <fullName>End User Desktop</fullName>
            </value>
            <value>
                <fullName>Ex end user Cloud</fullName>
            </value>
            <value>
                <fullName>Ex end user Desktop</fullName>
            </value>
            <value>
                <fullName>ISV</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ex Partner</fullName>
            </value>
            <value>
                <fullName>National Partner</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
                <isActive>false</isActive>
                <label>Dead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enhancement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Amount__c</fullName>
    <label>OLD_Enhancement ARR (Acct)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enhancement_Date__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Date__c</fullName>
    <label>Enhancement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enhancement_Status__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Status__c</fullName>
    <label>Enhancement Status List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Churned</fullName>
            </value>
            <value>
                <fullName>Needs Attention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Enhancement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Amount__c</fullName>
    <formula>Account.Total_ARR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OLD_Current ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enhancement_Status__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Status__c</fullName>
    <formula>Account.Enhancement_Status_Formula_Field__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enhancement Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Logo</fullName>
            </value>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Change Order (Services)</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
                <isActive>false</isActive>
                <label>Software</label>
            </value>
            <value>
                <fullName>Subscription</fullName>
                <isActive>false</isActive>
                <label>Subscription</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Renewals</businessProcess>
    <description>Renewal Opportunities</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {

    public static void handleBeforeInsertAndUpdate(List<Account> accounts, Map<Id, Account> oldMap) {
        for(Account acc : accounts) {
            Account oldAcc = oldMap?.get(acc.Id);

            // If ABR Scheduled Date is being populated for the first time, stamp the datetime
            if(acc.ABR_Scheduled_Date__c != null && oldAcc?.ABR_Scheduled_Date__c == null && acc.ABR_Scheduled_Date_Set__c == null) {
                acc.ABR_Scheduled_Date_Set__c = DateTime.now();
            }

            // If ABR Happened is being set to true for the first time, stamp the datetime
            if(acc.ABR_Happened__c == true && oldAcc?.ABR_Happened__c != true && acc.ABR_Happened_Set__c == null) {
                acc.ABR_Happened_Set__c = DateTime.now();
            }
        }
    }

    public static void handleAfterInsertAndUpdate(Map<Id, Account> accounts, Map<Id,Account> oldMap) {
        //first collect the Accounts we should work with
        Map<Id, Account> accountsNeedingWork = new Map<Id, Account>();
        for(Account acc : accounts.values()) {
            if(shouldAccountBeProcessed(acc, oldMap?.get(acc.Id)))
                accountsNeedingWork.put(acc.Id, acc);
        }
        if(accountsNeedingWork.isEmpty()) return;

        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        //Now lets get a list of Open Renewal Opportunities for these Accounts
        List<Opportunity> openRenewalOpps = [   SELECT Id, AccountId, StageName, CloseDate, Amount
                                                FROM Opportunity 
                                                WHERE AccountId IN :accountsNeedingWork.keySet()
                                                AND IsClosed = False
                                                AND Subtype__c = 'Renewal'];

        //if there are existing Renewals, we will need to either Update the Opportunity to match new info if the Opportunity is still valid OR Close Won the Opportunity
        for(Opportunity opp : openRenewalOpps) {
            Account acc = accounts.get(opp.AccountId); //we are grabbing the account from the accounts map just in case there are duplicate Opportunities for an account
            //now, do we Close Won the Opp, or do we update it and keep it open?  We will determine this by looking at the dates.
            Integer daysDifference = opp.CloseDate.daysBetween(acc.Enhancement_Date__c);
            if(daysDifference > -60 && daysDifference < 60) {
                //the Opportunity is within 60 days of the Account Enhancement Date (which is at least annually), 
                //so let's update the Opportunity to have the right info on the account
                opp.CloseDate = acc.Enhancement_Date__c;
                opp.Amount = acc.Enhancement_Amount__c;
                oppsToUpdate.add(opp);
                if(accountsNeedingWork.containsKey(opp.AccountId))
                    accountsNeedingWork.remove(opp.AccountId); //We've processed this Account
            }
            else {
                opp.StageName = 'Closed Won';
                oppsToUpdate.add(opp);
                //we are NOT removing the Account from AccountsNeedingWork as we still need to create a NEW Opportunity for them
            }
        }
        if(!oppsToUpdate.isEmpty()) {
            update oppsToUpdate;
        }
    }

    public static Boolean shouldAccountBeProcessed(Account acc, Account oldAcc) {
        //make sure we have fields to even process with
        if(acc?.Enhancement_Status__c != 'Current' || acc?.Enhancement_Amount__c == null || acc?.Enhancement_Date__c == null)
            return false;
        
        //make sure the account type is something we want to process
        if(acc.Type == 'Client - Direct' || acc.Type == 'Client - Registered to Partner' || acc.Type == 'End User') {
            //ok these are good types
            if(acc.Type == 'End User' && (acc.Customer_Class__c == 'Ex end user Cloud' || acc.Customer_Class__c == 'Ex end user Desktop'))
                return false; //we don't want End User IF they are Ex end users
        }
        else //the Account is NOT one of the 3 Account Types we care about
            return false;

        //lets see if the values changed
        if(oldAcc != null) {
            if(acc.Enhancement_Amount__c == oldAcc.Enhancement_Amount__c &&
                    acc.Enhancement_Date__c == oldAcc.Enhancement_Date__c &&
                    acc.Enhancement_Status__c == oldAcc.Enhancement_Status__c)
                return false; //None of the Enhancement Fields changed
        }

        //ok, looks like we passed all of our validations to see if this Account should be processed!
        return true;
    }
}