force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Promoter</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
                <default>true</default>
                <label>Satisfied</label>
            </value>
            <value>
                <fullName>Unsatisfied</fullName>
            </value>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Future Churn</fullName>
            </value>
            <value>
                <fullName>Churned</fullName>
            </value>
            <value>
                <fullName>Moving to Business Central</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/chargebeeapps__CB_Site__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__CB_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargebee Site</label>
    <referenceTo>chargebeeapps__CB_Sites__c</referenceTo>
    <relationshipLabel>CB Customers</relationshipLabel>
    <relationshipName>CB_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enhancement_Date__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Date__c</fullName>
    <label>Enhancement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>An End-User of one or more SalesPad products</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Account.Account_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Business_Segment__c</fullName>
    <label>Business Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesPad</fullName>
            </value>
            <value>
                <fullName>SalesPad for BC</fullName>
            </value>
            <value>
                <fullName>Profit Max Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Manual_Discount__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Manual_Discount__c</fullName>
    <label>Manual Discount</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source_Global__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source_Global__c</fullName>
    <label>Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/New_Business.recordType-meta.xml
<RecordType>
    <fullName>New_Business</fullName>
    <active>true</active>
    <businessProcess>New Business</businessProcess>
    <description>Use this for all standard opportunities for new and existing business</description>
    <label>New Business</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/chargebeeapps__CB_Site__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__CB_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CB Site</label>
    <referenceTo>chargebeeapps__CB_Sites__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Cavallo</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA)-INS | salespadllcdbacavallosolutions1644863490847.cavallo_profit_scan</fullName>
    </customValue>
    <customValue>
        <fullName>PMP AA</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA) - INS</fullName>
        <isActive>false</isActive>
        <label>AppSource (SPZA) - INS</label>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandler_Test.cls
@isTest
private class QuoteTriggerHandler_Test {
    
    @IsTest(SeeAllData=true)
    static void testQuoteBeforeInsert(){
            RecordType acctRecordType = [Select ID,DeveloperName From RecordType where DeveloperName='Customer' limit 1];
            RecordType oppRecordType = [Select ID,DeveloperName From RecordType where DeveloperName='New_Business' limit 1];
            //chargebeeapps__CB_Sites__c cbSite = [Select ID From chargebeeapps__CB_Sites__c limit 1];
            Account acct = new Account();
            acct.Name = 'Test Account 1';
            acct.Type = 'Client - Direct';
            acct.RecordType = acctRecordType;
            acct.Account_Status__c = 'Satisfied';
            //acct.chargebeeapps__CB_Site__c = cbSite.Id;
            acct.Enhancement_Date__c = Date.Today().addYears(2);
            Pricebook2 pb = [Select ID From Pricebook2 where isActive = true AND Name Like '%CB Standard%' limit 1];
    
            Opportunity opp = new Opportunity();
            opp.Name = 'Opp Test';
            opp.AccountId = acct.Id;
            opp.Type = 'Existing Business';
            opp.chargebeeapps__Manual_Discount__c = '[{"type":"PERCENTAGE","period_unit":"year","period":"1","percentage":null,"operation_type":"add","item_price_id":"CLD00018","isPercentageDiscount":true,"isOneTime":false,"isLineItemDiscount":true,"isInvoiceDiscount":false,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"limited_period","discountType":"PERCENTAGE","discountPercentage":"5.00","discountAmount":null,"currency_code":"USD","cbId":"D_542421","apply_on":"specific_item_price","amount":null}]';
            opp.StageName = 'Structure';
            opp.CloseDate = Date.Today().addMonths(3);
            opp.Opportunity_Source_Global__c = 'Customer';
            opp.Pricebook2Id = pb.Id;
            opp.RecordTypeId = oppRecordType.Id;
            opp.Business_Segment__c = 'SalesPad';
            insert opp;
            Quote q = new Quote(OpportunityId = opp.Id);
            q.Name = 'Ray Test';
        	QuoteLineDiscount qdiscount = new QuoteLineDiscount();
        	qdiscount.type = 'PERCENTAGE';
        	qdiscount.percentage = '25';
        	qdiscount.operation_type = 'add';
        	qdiscount.item_price_id = 'CLD00018';
        	qdiscount.isPercentageDiscount = true;
            qdiscount.isOneTime = false;
            qdiscount.isLineItemDiscount = true;
            qdiscount.isInvoiceDiscount = false;
            qdiscount.isForever = false;
            qdiscount.isFixedDiscount = false;
            qdiscount.discountPercentage = '25';
            qdiscount.discountAmount = '100';
            qdiscount.currency_code = 'USD';
            qdiscount.cbId = 'cbId1234';
            qdiscount.apply_on = 'specific_item_price';
            qdiscount.amount = '100';
        	qdiscount.id = 'discountId';
            Test.startTest();
            insert q;
            Test.stopTest();
        }
    }