force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Promoter</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
                <default>true</default>
                <label>Satisfied</label>
            </value>
            <value>
                <fullName>Unsatisfied</fullName>
            </value>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Future Churn</fullName>
            </value>
            <value>
                <fullName>Churned</fullName>
            </value>
            <value>
                <fullName>Moving to Business Central</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/chargebeeapps__CB_Site__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__CB_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargebee Site</label>
    <referenceTo>chargebeeapps__CB_Sites__c</referenceTo>
    <relationshipLabel>CB Customers</relationshipLabel>
    <relationshipName>CB_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Class__c.field-meta.xml
<CustomField>
    <fullName>Customer_Class__c</fullName>
    <inlineHelpText>Original customer class - taken from ERP</inlineHelpText>
    <label>Customer Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End User Cloud</fullName>
            </value>
            <value>
                <fullName>End User Desktop</fullName>
            </value>
            <value>
                <fullName>Ex end user Cloud</fullName>
            </value>
            <value>
                <fullName>Ex end user Desktop</fullName>
            </value>
            <value>
                <fullName>ISV</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ex Partner</fullName>
            </value>
            <value>
                <fullName>National Partner</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
                <isActive>false</isActive>
                <label>Dead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enhancement_Date__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Date__c</fullName>
    <label>Enhancement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Derived from Assigned Partner picklist</description>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Level__c.field-meta.xml
<CustomField>
    <fullName>Partner_Level__c</fullName>
    <label>Economic Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold Plus</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>An End-User of one or more SalesPad products</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Reseller.recordType-meta.xml
<RecordType>
    <fullName>Reseller</fullName>
    <active>false</active>
    <description>A Reseller/VAR</description>
    <label>Reseller</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Reseller_Partner.recordType-meta.xml
<RecordType>
    <fullName>Reseller_Partner</fullName>
    <active>true</active>
    <label>Reseller Partner</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Account.Account_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Business_Segment__c</fullName>
    <label>Business Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesPad</fullName>
            </value>
            <value>
                <fullName>SalesPad for BC</fullName>
            </value>
            <value>
                <fullName>Profit Max Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Manual_Discount__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Manual_Discount__c</fullName>
    <label>Manual Discount</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Subscription_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Id</label>
    <referenceTo>chargebeeapps__CB_Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct_v_Partner__c.field-meta.xml
<CustomField>
    <fullName>Direct_v_Partner__c</fullName>
    <inlineHelpText>Is this being sold through a partner, or directly to the end user?</inlineHelpText>
    <label>Direct v Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existing_GP_or_New_GP__c.field-meta.xml
<CustomField>
    <fullName>Existing_GP_or_New_GP__c</fullName>
    <inlineHelpText>Does the person you&apos;re selling this to already own Dynamics GP, or will they also be purchasing Dynamics GP?</inlineHelpText>
    <label>Existing GP or New GP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing GP</fullName>
            </value>
            <value>
                <fullName>New GP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Coupon_Applied__c.field-meta.xml
<CustomField>
    <fullName>Is_Coupon_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Coupon Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Quote_Approved__c.field-meta.xml
<CustomField>
    <fullName>Is_Quote_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to check if related Quote is Approved.</description>
    <label>Is Quote Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Manual_Discount__c.field-meta.xml
<CustomField>
    <fullName>Manual_Discount__c</fullName>
    <label>Manual Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source_Global__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source_Global__c</fullName>
    <label>Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Identify the partner involved in this deal.  If this is a direct deal, leave this blank</inlineHelpText>
    <label>Partner for Margin</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunities</relationshipLabel>
    <relationshipName>OpportunitiesPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Sales Engineer, Project Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Logo</fullName>
            </value>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Change Order (Services)</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
                <isActive>false</isActive>
                <label>Software</label>
            </value>
            <value>
                <fullName>Subscription</fullName>
                <isActive>false</isActive>
                <label>Subscription</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Year_One__c.field-meta.xml
<CustomField>
    <fullName>Year_One__c</fullName>
    <label>Year One</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Year_Three__c.field-meta.xml
<CustomField>
    <fullName>Year_Three__c</fullName>
    <label>Year Three</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Year_Two__c.field-meta.xml
<CustomField>
    <fullName>Year_Two__c</fullName>
    <label>Year Two</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <businessProcess>Custom</businessProcess>
    <label>Custom</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/New_Business.recordType-meta.xml
<RecordType>
    <fullName>New_Business</fullName>
    <active>true</active>
    <businessProcess>New Business</businessProcess>
    <description>Use this for all standard opportunities for new and existing business</description>
    <label>New Business</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Renewals</businessProcess>
    <description>Renewal Opportunities</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/chargebeeapps__CB_Item_Price__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__CB_Item_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CB Item Price</label>
    <referenceTo>chargebeeapps__CB_Item_Price__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Opportunity.Partner__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/Partner_Client_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner-Client Relationship</label>
    <nameField>
        <label>Partner-Client Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner-Client Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships</relationshipLabel>
    <relationshipName>Partner_Client_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Margin_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Margin_Start_Date__c</fullName>
    <label>Margin Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Client_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner_of_Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_of_Record_Status__c</fullName>
    <label>Partner of Record Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/chargebeeapps__CB_Site__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__CB_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CB Site</label>
    <referenceTo>chargebeeapps__CB_Sites__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Cavallo</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA)-INS | salespadllcdbacavallosolutions1644863490847.cavallo_profit_scan</fullName>
    </customValue>
    <customValue>
        <fullName>PMP AA</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA) - INS</fullName>
        <isActive>false</isActive>
        <label>AppSource (SPZA) - INS</label>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandler_Test.cls
@isTest
public class OpportunityTriggerHandler_Test {

    private static final String ACCOUNT_TYPE_CLIENT = 'Client';
    private static final String ACCOUNT_TYPE_PROSPECT = 'Prospect';
    private static final String STAGE_CLOSED_WON = 'Closed Won';
    private static final String STAGE_QUALIFY = 'Qualify';
    private static final String RECORD_TYPE_NEW_BUSINESS = 'New_Business';
    private static final String OPPORTUNITY_TYPE_RENEWAL = 'Renewal';

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static Id getNewBusinessRecTypeId() {
        return Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
            .get(RECORD_TYPE_NEW_BUSINESS).getRecordTypeId();
    }

    private static Account createAccount() {
        Account acc = new Account(Name = 'Test Account', Type = ACCOUNT_TYPE_PROSPECT);
        insert acc;
        return acc;
    }

    private static chargebeeapps__CB_Subscription__c createSubscription(Id accountId, Decimal mrr) {
        chargebeeapps__CB_Subscription__c sub = new chargebeeapps__CB_Subscription__c(
            chargebeeapps__Company__c = accountId,
            chargebeeapps__MRR__c = mrr
        );
        insert sub;
        return sub;
    }

    private static Opportunity buildRenewalOpp(Id accountId, Id recTypeId, Id subId,
                                               Decimal yearOne, Decimal yearTwo, Decimal yearThree) {
        return new Opportunity(
            Name = 'Test Renewal Opportunity',
            AccountId = accountId,
            StageName = STAGE_QUALIFY,
            CloseDate = Date.today().addDays(30),
            RecordTypeId = recTypeId,
            Type = OPPORTUNITY_TYPE_RENEWAL,
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true,
            chargebeeapps__Subscription_Id__c = subId,
            Year_One__c = yearOne,
            Year_Two__c = yearTwo,
            Year_Three__c = yearThree
        );
    }

    // ── Before Insert: Default Pricebook ─────────────────────────────────────

    @isTest
    static void testDefaultPricebook() {
        OpportunityTriggerHandler.fa.Default_Pricebook_Id__c = true;

        Pricebook2 pb = new Pricebook2(IsActive = true, Name = 'Dealer - Gold');
        insert pb;

        Account a = new Account(Name = 'Ray Test', Partner_Level__c = 'Gold', Type = 'Other', Customer_Class__c = 'Other');
        insert a;

        Opportunity opp = new Opportunity(
            AccountId = a.Id,
            StageName = 'Sandbox',
            CloseDate = Date.today(),
            Name = 'Ray Test',
            Existing_GP_or_New_GP__c = 'Existing GP',
            Sales_Engineer__c = '0056A000002zXKeQAM',
            Direct_v_Partner__c = 'Partner',
            Business_Segment__c = 'SalesPad'
        );

        Test.startTest();
        insert opp;
        Test.stopTest();
    }

    // ── After Update: Partner Margin / Subscription Change ────────────────────

    @IsTest(SeeAllData=true)
    static void testCBSubPartnerMargin() {
        try {
            RecordType acctRecordType = [SELECT ID FROM RecordType WHERE DeveloperName = 'Customer' LIMIT 1];
            RecordType acctPartnerResellerRecordType = [SELECT ID FROM RecordType WHERE DeveloperName = 'Reseller_Partner' LIMIT 1];
            RecordType oppRecordType = [SELECT ID FROM RecordType WHERE DeveloperName = 'Cloud' LIMIT 1];

            List<chargebeeapps__CB_Sites__c> cbSites = [SELECT ID FROM chargebeeapps__CB_Sites__c LIMIT 1];
            if (cbSites.isEmpty()) {
                System.assert(true, 'No Chargebee sites found - skipping test');
                return;
            }
            chargebeeapps__CB_Sites__c cbSite = cbSites[0];

            Account acct = new Account(
                Name = 'Test Account 1',
                Type = 'Client - Direct',
                RecordType = acctRecordType,
                Account_Status__c = 'Satisfied',
                chargebeeapps__CB_Site__c = cbSite.Id,
                Enhancement_Date__c = Date.today().addYears(2)
            );
            insert acct;

            Account partnerAcct = new Account(Name = 'Partner Account 1', Type = 'Partner - Reseller', RecordType = acctPartnerResellerRecordType);
            insert partnerAcct;

            Account partnerAcct2 = new Account(Name = 'Partner Account 2', Type = 'Partner - Reseller', RecordType = acctPartnerResellerRecordType);
            insert partnerAcct2;

            Partner_Client_Relationship__c pcr = new Partner_Client_Relationship__c(
                Client__c = acct.Id,
                Partner__c = partnerAcct.Id,
                Partner_of_Record_Status__c = 'Current',
                Margin_Start_Date__c = Date.today(),
                Partner_Client_Margin_Eligibility__c = 'Active'
            );
            insert pcr;

            Pricebook2 pb = [SELECT ID FROM Pricebook2 WHERE isActive = true AND Name LIKE '%CB Standard%' ORDER BY CreatedDate DESC LIMIT 1];

            Opportunity opp = new Opportunity(
                Name = 'Opp Test',
                AccountId = acct.Id,
                Partner__c = partnerAcct.Id,
                Type = 'Existing Business',
                Subtype__c = 'Add-On',
                chargebeeapps__Manual_Discount__c = '[{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"25.00","discountAmount":null,"currency_code":"USD","cbId":"D_744989","apply_on":"invoice_amount","amount":null}]',
                StageName = 'Structure',
                CloseDate = Date.today().addMonths(3),
                Opportunity_Source_Global__c = 'Customer',
                Pricebook2Id = pb.Id,
                RecordTypeId = oppRecordType.Id,
                Is_Coupon_Applied__c = true,
                Business_Segment__c = 'SalesPad'
            );
            insert opp;

            chargebeeapps__CB_Item_Price__c cbItemPrice = [SELECT ID FROM chargebeeapps__CB_Item_Price__c WHERE Name = 'AUTOMATION AGENT - SUB USD Yearly' LIMIT 1];
            chargebeeapps__CB_Item_Price__c cbItemPrice2 = [SELECT ID FROM chargebeeapps__CB_Item_Price__c WHERE Name = 'AUTOMATION AGENT ENHANCEMENT' LIMIT 1];
            Product2 product = [SELECT ID FROM Product2 WHERE Name = 'AUTOMATION AGENT - SUB' AND IsActive = true LIMIT 1];
            Product2 product2 = [SELECT ID FROM Product2 WHERE Name = 'AUTOMATION AGENT ENHANCEMENT' AND IsActive = true LIMIT 1];
            PricebookEntry pbEntry2 = [SELECT ID FROM PricebookEntry WHERE Name = 'AUTOMATION AGENT ENHANCEMENT' AND IsActive = true AND Pricebook2Id = :pb.Id LIMIT 1];

            OpportunityLineItem oppProduct = new OpportunityLineItem(
                OpportunityId = opp.Id, Product2Id = product.Id, Quantity = 1, Discount = 25,
                chargebeeapps__CB_Item_Price__c = cbItemPrice.Id
            );
            OpportunityLineItem oppProduct2 = new OpportunityLineItem(
                OpportunityId = opp.Id, Product2Id = product2.Id, Quantity = 1, Discount = 25,
                chargebeeapps__CB_Item_Price__c = cbItemPrice2.Id, PricebookEntryId = pbEntry2.Id
            );
            insert new List<OpportunityLineItem>{ oppProduct, oppProduct2 };

            Test.startTest();
            opp.Partner__c = partnerAcct2.Id;
            update opp;
            Test.stopTest();
        } catch (Exception e) {
            System.assert(true, 'Test completed with exception: ' + e.getMessage());
        }
    }

    @isTest
    static void testAfterUpdate_SubscriptionIdChange_ExecutesPMUpdatePath() {
        Account testAccount = createAccount();

        chargebeeapps__CB_Subscription__c sub1 = createSubscription(testAccount.Id, 500);
        chargebeeapps__CB_Subscription__c sub2 = createSubscription(testAccount.Id, 750);

        Opportunity testOpp = new Opportunity(
            Name = 'Subscription Change Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true,
            chargebeeapps__Subscription_Id__c = sub1.Id
        );
        insert testOpp;

        Opportunity oppToUpdate = [SELECT Id, chargebeeapps__Subscription_Id__c FROM Opportunity WHERE Id = :testOpp.Id];
        oppToUpdate.chargebeeapps__Subscription_Id__c = sub2.Id;

        Test.startTest();
        update oppToUpdate;
        Test.stopTest();

        Opportunity result = [SELECT chargebeeapps__Subscription_Id__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(sub2.Id, result.chargebeeapps__Subscription_Id__c,
            'Subscription ID should be updated to the new subscription');
    }

    // ── Before Update: Manual Discount ────────────────────────────────────────

    @isTest
    static void testUpdateManualDiscountWithPercentageDiscount() {
        Account testAccount = new Account(Name = 'Test Account for Manual Discount');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Manual Discount',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"33.40","discountAmount":null,"currency_code":"USD","cbId":"D_978527","apply_on":"invoice_amount","amount":null},{"type":"FIXED_AMOUNT","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":false,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":true,"id":null,"duration_type":"one_time","discountType":"FIXED_AMOUNT","discountPercentage":null,"discountAmount":"223.00","currency_code":"USD","cbId":"D_403513","apply_on":"invoice_amount","amount":"223.00"}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(33.40, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be 33.40%');
        System.assertEquals(223.00, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be 223.00');
    }

    @isTest
    static void testUpdateManualDiscountWithMultiplePercentageDiscounts() {
        Account testAccount = new Account(Name = 'Test Account for Multiple Discounts');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Multiple Discounts',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"25.00","discountAmount":null,"currency_code":"USD","cbId":"D_978527","apply_on":"invoice_amount","amount":null},{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":"DPE00001","isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":true,"isInvoiceDiscount":false,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"15.00","discountAmount":null,"currency_code":"USD","cbId":"D_128587","apply_on":"specific_item_price","amount":null}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(25.00, updatedOpp.Manual_Discount__c, 'Should use first invoice-level percentage discount');
        System.assertEquals(null, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be null');
    }

    @isTest
    static void testUpdateManualDiscountWithNoPercentageDiscount() {
        Account testAccount = new Account(Name = 'Test Account for No Percentage');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for No Percentage',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"FIXED_AMOUNT","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":false,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":true,"id":null,"duration_type":"one_time","discountType":"FIXED_AMOUNT","discountPercentage":null,"discountAmount":"223.00","currency_code":"USD","cbId":"D_403513","apply_on":"invoice_amount","amount":"223.00"}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be null when no percentage discount');
        System.assertEquals(223.00, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be 223.00');
    }

    @isTest
    static void testUpdateManualDiscountWithLineItemOnlyPercentage() {
        Account testAccount = new Account(Name = 'Test Account for Line Item Only');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Line Item Only',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":"DPE00001","isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":true,"isInvoiceDiscount":false,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"10.00","discountAmount":null,"currency_code":"USD","cbId":"D_128587","apply_on":"specific_item_price","amount":null}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be null when percentage is not invoice level');
        System.assertEquals(null, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be null');
    }

    @isTest
    static void testUpdateManualDiscountWithInvalidJson() {
        Account testAccount = new Account(Name = 'Test Account for Invalid JSON');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Invalid JSON',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = 'invalid json data';
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be null with invalid JSON');
        System.assertEquals(null, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be null with invalid JSON');
    }

    @isTest
    static void testUpdateManualDiscountWithEmptyJson() {
        Account testAccount = new Account(Name = 'Test Account for Empty JSON');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Empty JSON',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = '[]';
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be null with empty JSON array');
        System.assertEquals(null, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be null with empty JSON array');
    }

    @isTest
    static void testUpdateManualDiscountWithNullJson() {
        Account testAccount = new Account(Name = 'Test Account for Null JSON');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Null JSON',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = null;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be null with null JSON');
        System.assertEquals(null, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be null with null JSON');
    }

    @isTest
    static void testUpdateManualDiscountWithFixedAmountOnly() {
        Account testAccount = new Account(Name = 'Test Account for Fixed Amount Only');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Fixed Amount Only',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"FIXED_AMOUNT","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":false,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":true,"id":null,"duration_type":"one_time","discountType":"FIXED_AMOUNT","discountPercentage":null,"discountAmount":"150.50","currency_code":"USD","cbId":"D_403513","apply_on":"invoice_amount","amount":"150.50"}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be null when no percentage discount');
        System.assertEquals(150.50, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be 150.50');
    }

    @isTest
    static void testUpdateManualDiscountWithMixedDiscounts() {
        Account testAccount = new Account(Name = 'Test Account for Mixed Discounts');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Mixed Discounts',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"15.75","discountAmount":null,"currency_code":"USD","cbId":"D_978527","apply_on":"invoice_amount","amount":null},{"type":"FIXED_AMOUNT","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":false,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":true,"id":null,"duration_type":"one_time","discountType":"FIXED_AMOUNT","discountPercentage":null,"discountAmount":"75.25","currency_code":"USD","cbId":"D_403513","apply_on":"invoice_amount","amount":"75.25"}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(15.75, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be 15.75%');
        System.assertEquals(75.25, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be 75.25');
    }

    @isTest
    static void testUpdateManualDiscountWithDecimalPrecision() {
        Account testAccount = new Account(Name = 'Test Account for Decimal Precision');
        insert testAccount;

        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Decimal Precision',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;

        String testJsonData = '[{"type":"PERCENTAGE","period_unit":null,"period":null,"percentage":null,"operation_type":"add","item_price_id":null,"isPercentageDiscount":true,"isOneTime":true,"isLineItemDiscount":false,"isInvoiceDiscount":true,"isForever":false,"isFixedDiscount":false,"id":null,"duration_type":"one_time","discountType":"PERCENTAGE","discountPercentage":"12.345","discountAmount":null,"currency_code":"USD","cbId":"D_978527","apply_on":"invoice_amount","amount":null}]';

        Test.startTest();
        testOpp.chargebeeapps__Manual_Discount__c = testJsonData;
        update testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Manual_Discount__c, Manual_Discount_Fixed__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(12.345, updatedOpp.Manual_Discount__c, 'Manual_Discount__c should be 12.345%');
        System.assertEquals(null, updatedOpp.Manual_Discount_Fixed__c, 'Manual_Discount_Fixed__c should be null');
    }

    // ── Before Insert: Auto Populate Sales Engineer ───────────────────────────

    @isTest
    static void testAutoPopulateSalesEngineerForNewBusiness() {
        Account testAccount = new Account(Name = 'Test Account for Sales Engineer');
        insert testAccount;

        RecordType newBusinessRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'New_Business' LIMIT 1];

        Test.startTest();
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Sales Engineer',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            RecordTypeId = newBusinessRecordType.Id,
            Type = 'New Logo',
            Business_Segment__c = 'SalesPad for BC'
        );
        insert testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Sales_Engineer__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertNotEquals(null, updatedOpp, 'Opportunity should be inserted successfully');
    }

    @isTest
    static void testAutoPopulateSalesEngineerForProfitMaxPlatform() {
        Account testAccount = new Account(Name = 'Test Account for Profit Max');
        insert testAccount;

        RecordType newBusinessRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'New_Business' LIMIT 1];

        Test.startTest();
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Profit Max',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            RecordTypeId = newBusinessRecordType.Id,
            Type = 'New Logo',
            Business_Segment__c = 'Profit Max Platform'
        );
        insert testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Sales_Engineer__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertNotEquals(null, updatedOpp, 'Opportunity should be inserted successfully');
    }

    @isTest
    static void testNoAutoPopulateForExpansionServicesOnly() {
        Account testAccount = new Account(Name = 'Test Account for Expansion Services');
        insert testAccount;

        RecordType newBusinessRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'New_Business' LIMIT 1];

        Test.startTest();
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Expansion Services',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            RecordTypeId = newBusinessRecordType.Id,
            Type = 'Expansion - Services only',
            Business_Segment__c = 'SalesPad for BC'
        );
        insert testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Sales_Engineer__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Sales_Engineer__c, 'Sales Engineer should NOT be auto-populated for Expansion - Services only');
    }

    @isTest
    static void testNoAutoPopulateForRenewal() {
        Account testAccount = new Account(Name = 'Test Account for Renewal');
        insert testAccount;

        RecordType newBusinessRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'New_Business' LIMIT 1];

        Test.startTest();
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Renewal',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            RecordTypeId = newBusinessRecordType.Id,
            Type = 'Renewal',
            Business_Segment__c = 'SalesPad for BC'
        );
        insert testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Sales_Engineer__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Sales_Engineer__c, 'Sales Engineer should NOT be auto-populated for Renewal');
    }

    @isTest
    static void testNoAutoPopulateForWrongBusinessSegment() {
        Account testAccount = new Account(Name = 'Test Account for Wrong Segment');
        insert testAccount;

        RecordType newBusinessRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'New_Business' LIMIT 1];

        Test.startTest();
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Wrong Segment',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            RecordTypeId = newBusinessRecordType.Id,
            Type = 'New Logo',
            Business_Segment__c = 'SalesPad'
        );
        insert testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Sales_Engineer__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Sales_Engineer__c, 'Sales Engineer should NOT be auto-populated for wrong business segment');
    }

    @isTest
    static void testNoAutoPopulateForWrongRecordType() {
        Account testAccount = new Account(Name = 'Test Account for Wrong Record Type');
        insert testAccount;

        RecordType customRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Custom' LIMIT 1];

        Test.startTest();
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity for Wrong Record Type',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            RecordTypeId = customRecordType.Id,
            Type = 'New Logo',
            Business_Segment__c = 'SalesPad for BC'
        );
        insert testOpp;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Sales_Engineer__c FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals(null, updatedOpp.Sales_Engineer__c, 'Sales Engineer should NOT be auto-populated for wrong record type');
    }

    // ── After Update: Closed Won → Account Type ───────────────────────────────

    @isTest
    static void testAfterUpdate_OpportunityClosedWon_SetsAccountTypeToClient() {
        Account acc = new Account(Name = 'Test Account', Type = ACCOUNT_TYPE_PROSPECT);
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = acc.Id,
            StageName = STAGE_QUALIFY,
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true
        );
        insert opp;

        Opportunity oppToUpdate = [SELECT Id, StageName FROM Opportunity WHERE Id = :opp.Id];
        oppToUpdate.StageName = STAGE_CLOSED_WON;

        Test.startTest();
        update oppToUpdate;
        Test.stopTest();

        Account updatedAccount = [SELECT Type FROM Account WHERE Id = :acc.Id];
        System.assertEquals(ACCOUNT_TYPE_CLIENT, updatedAccount.Type,
            'Account Type should be set to Client when opportunity is closed won');
    }

    @isTest
    static void testAfterUpdate_AccountAlreadyClient_DoesNotUpdate() {
        Account acc = new Account(Name = 'Test Account', Type = ACCOUNT_TYPE_CLIENT);
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = acc.Id,
            StageName = STAGE_QUALIFY,
            CloseDate = Date.today().addDays(30),
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true
        );
        insert opp;

        Opportunity oppToUpdate = [SELECT Id, StageName FROM Opportunity WHERE Id = :opp.Id];
        oppToUpdate.StageName = STAGE_CLOSED_WON;

        Test.startTest();
        update oppToUpdate;
        Test.stopTest();

        Account updatedAccount = [SELECT Type FROM Account WHERE Id = :acc.Id];
        System.assertEquals(ACCOUNT_TYPE_CLIENT, updatedAccount.Type,
            'Account Type should remain Client when already set');
    }

    // ── Before Insert / Before Update: Renewal Estimated Value ───────────────

    @isTest
    static void testBeforeInsert_AllThreeYearsPopulated_CalculatesCorrectAverage() {
        // MRR=1000 → ARR=12000; avg=(3000+6000+9000)/3=6000; estimated=6000
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 1000);

        Test.startTest();
        Opportunity opp = buildRenewalOpp(acc.Id, getNewBusinessRecTypeId(), sub.Id, 3000, 6000, 9000);
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(6000, result.Estimated_Value__c,
            'Estimated Value should be ARR minus average of all three years');
    }

    @isTest
    static void testBeforeInsert_OnlyYearsGreaterThanZeroCountedInAverage() {
        // MRR=1000 → ARR=12000; Year_One=6000, Year_Two=0, Year_Three=0
        // Only 1 year > 0 → avg=6000/1=6000; estimated=6000
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 1000);

        Test.startTest();
        Opportunity opp = buildRenewalOpp(acc.Id, getNewBusinessRecTypeId(), sub.Id, 6000, 0, 0);
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(6000, result.Estimated_Value__c,
            'Average should divide only by the count of years greater than zero');
    }

    @isTest
    static void testBeforeInsert_TwoYearsGreaterThanZero_AverageUsesCorrectDivisor() {
        // MRR=1000 → ARR=12000; Year_One=6000, Year_Two=9000, Year_Three=0
        // 2 years > 0 → avg=(6000+9000)/2=7500; estimated=4500
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 1000);

        Test.startTest();
        Opportunity opp = buildRenewalOpp(acc.Id, getNewBusinessRecTypeId(), sub.Id, 6000, 9000, 0);
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(4500, result.Estimated_Value__c,
            'Average should use 2 as divisor when only two years are greater than zero');
    }

    @isTest
    static void testBeforeInsert_NegativeResult_ClampedToZero() {
        // MRR=500 → ARR=6000; Year_One=24000 → avg=24000; 6000-24000 < 0 → 0
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 500);

        Test.startTest();
        Opportunity opp = buildRenewalOpp(acc.Id, getNewBusinessRecTypeId(), sub.Id, 24000, 0, 0);
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(0, result.Estimated_Value__c,
            'Estimated Value should be clamped to zero when result is negative');
    }

    @isTest
    static void testBeforeInsert_NoSubscriptionMatch_MrrDefaultsToZero() {
        // Subscription exists but MRR is null → ARR=0; avg=6000; 0-6000 < 0 → 0
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, null);

        Test.startTest();
        Opportunity opp = buildRenewalOpp(acc.Id, getNewBusinessRecTypeId(), sub.Id, 6000, 0, 0);
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(0, result.Estimated_Value__c,
            'Estimated Value should be zero when subscription MRR is null');
    }

    @isTest
    static void testBeforeInsert_NonRenewalType_DoesNotSetEstimatedValue() {
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 1000);

        Test.startTest();
        Opportunity opp = new Opportunity(
            Name = 'New Logo Opportunity',
            AccountId = acc.Id,
            StageName = STAGE_QUALIFY,
            CloseDate = Date.today().addDays(30),
            RecordTypeId = getNewBusinessRecTypeId(),
            Type = 'New Logo',
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true,
            chargebeeapps__Subscription_Id__c = sub.Id,
            Year_One__c = 6000
        );
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(null, result.Estimated_Value__c,
            'Estimated Value should not be calculated for non-Renewal opportunity types');
    }

    @isTest
    static void testBeforeInsert_NoSubscriptionId_DoesNotSetEstimatedValue() {
        Account acc = createAccount();

        Test.startTest();
        Opportunity opp = new Opportunity(
            Name = 'Renewal Without Subscription',
            AccountId = acc.Id,
            StageName = STAGE_QUALIFY,
            CloseDate = Date.today().addDays(30),
            RecordTypeId = getNewBusinessRecTypeId(),
            Type = OPPORTUNITY_TYPE_RENEWAL,
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true,
            Year_One__c = 6000
        );
        insert opp;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(null, result.Estimated_Value__c,
            'Estimated Value should not be calculated when no subscription ID is present');
    }

    @isTest
    static void testBeforeUpdate_YearFieldAdded_CalculatesEstimatedValue() {
        // Create opp without year fields, then update with year fields
        // MRR=1000 → ARR=12000; Year_One=3000, Year_Two=3000 → avg=3000; estimated=9000
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 1000);

        Opportunity opp = new Opportunity(
            Name = 'Renewal For Update',
            AccountId = acc.Id,
            StageName = STAGE_QUALIFY,
            CloseDate = Date.today().addDays(30),
            RecordTypeId = getNewBusinessRecTypeId(),
            Type = OPPORTUNITY_TYPE_RENEWAL,
            Business_Segment__c = 'SalesPad',
            Is_Quote_Approved__c = true,
            chargebeeapps__Subscription_Id__c = sub.Id
        );
        insert opp;

        Opportunity oppToUpdate = [SELECT Id FROM Opportunity WHERE Id = :opp.Id];
        oppToUpdate.Year_One__c = 3000;
        oppToUpdate.Year_Two__c = 3000;

        Test.startTest();
        update oppToUpdate;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(9000, result.Estimated_Value__c,
            'Estimated Value should be calculated on update when year fields are added');
    }

    @isTest
    static void testBeforeUpdate_YearsUpdated_RecalculatesEstimatedValue() {
        // Opp already has year fields; update changes them and recalculates
        // Change Year_One from 6000 to 3000 → avg=3000; estimated = 12000 - 3000 = 9000
        Account acc = createAccount();
        chargebeeapps__CB_Subscription__c sub = createSubscription(acc.Id, 1000);

        Opportunity opp = buildRenewalOpp(acc.Id, getNewBusinessRecTypeId(), sub.Id, 6000, 0, 0);
        insert opp;

        Opportunity oppToUpdate = [SELECT Id, Year_One__c FROM Opportunity WHERE Id = :opp.Id];
        oppToUpdate.Year_One__c = 3000;

        Test.startTest();
        update oppToUpdate;
        Test.stopTest();

        Opportunity result = [SELECT Estimated_Value__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(9000, result.Estimated_Value__c,
            'Estimated Value should be recalculated on update when year values change');
    }
}