force-app/main/default/objects/Account/fields/Active_Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Active_Partner_Tier__c</fullName>
    <label>Active Partner Tier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Derived from Assigned Partner picklist</description>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Alliance_Partner.recordType-meta.xml
<RecordType>
    <fullName>Alliance_Partner</fullName>
    <active>true</active>
    <label>Alliance Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Identify the partner involved in this deal.  If this is a direct deal, leave this blank</inlineHelpText>
    <label>Partner for Margin</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunities</relationshipLabel>
    <relationshipName>OpportunitiesPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Opportunity.Partner__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/Partner_Client_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner-Client Relationship</label>
    <nameField>
        <label>Partner-Client Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner-Client Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships</relationshipLabel>
    <relationshipName>Partner_Client_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Margin_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Margin_Start_Date__c</fullName>
    <label>Margin Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Client_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner_of_Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_of_Record_Status__c</fullName>
    <label>Partner of Record Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/Partner_Margin__c.object-meta.xml
<CustomObject>
    <label>Partner Margin</label>
    <nameField>
        <label>Partner Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Enhancement_Partner_Margin_Y1__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Partner_Margin_Y1__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>Enhancement - Partner Margin % (Y1)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins (Partner)</relationshipLabel>
    <relationshipName>Partner_Margins2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Billing_Type__c</fullName>
    <label>Partner Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill through Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold Plus</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Software_Partner_Margin_Y1__c.field-meta.xml
<CustomField>
    <fullName>Software_Partner_Margin_Y1__c</fullName>
    <label>Software - Partner Margin % (Y1)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/Partner_Tier__c.object-meta.xml
<CustomObject>
    <label>Partner Tier</label>
    <nameField>
        <label>Partner Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Tier__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Tiers</relationshipLabel>
    <relationshipName>Partner_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold Plus</fullName>
                <isActive>false</isActive>
                <label>Gold Plus</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier_Start_Date__c</fullName>
    <label>Partner Tier Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/PartnerTier_Status__c.field-meta.xml
<CustomField>
    <fullName>PartnerTier_Status__c</fullName>
    <label>Partner Tier Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtils.cls
@isTest(SeeAllData=true)
public class TestUtils {

    public static Account createAccount() {
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Type = 'Client - Direct'; 
        insert acc;
        return acc;
    }

    public static Account createPartnerAccount() {
        Account acc = new Account();
        acc.Name = 'Test Partner Account';
        acc.Type = 'Partner - Prospective';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Alliance_Partner').getRecordTypeId();
        acc.Active_Partner_Tier__c = 'Gold'; 
        insert acc;
        return acc;
    }

    public static Opportunity createOpportunity(Id accountId, Id partnerId) {
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.AccountId = accountId;
        opp.Partner__c = partnerId;
        opp.StageName = 'Prospecting'; 
        opp.CloseDate = Date.today().addDays(30);
        insert opp;
        opp = [SELECT Id, Name, AccountId, Partner__c, StageName, CloseDate, Pricebook2Id FROM Opportunity WHERE Id =: opp.Id LIMIT 1];
        return opp;
    }

    public static Product2 createProduct(String productName) {
        Product2 prod = new Product2();
        prod.Name = productName;
        insert prod;
        return prod;
    }

    public static PricebookEntry createPricebookEntry(Id pricebookId, Id productId, Decimal unitPrice) {
        insert new PriceBookEntry(Product2Id=productId, Pricebook2Id=Test.getStandardPricebookId(), UnitPrice=0);

        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = productId,
            UnitPrice = unitPrice,
            IsActive = true
        );

        insert pbe;
        return pbe;

    }

    public static OpportunityLineItem createOpportunityLineItem(Id opportunityId, Id pricebookEntryId) {
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opportunityId;
        oli.PricebookEntryId = pricebookEntryId;
        oli.Quantity = 1;
        oli.UnitPrice = 100.00; 
        insert oli;
        return oli;
    }

    public static Partner_Margin__c createPartnerMargin(Id oppId, Id partnerId, Id acctId){
        Partner_Margin__c testPartnerMargin = new Partner_Margin__c(
            Opportunity__c = oppId,
            Partner__c = partnerId,
            Software_Partner_Margin_Y1__c = 10,
            Enhancement_Partner_Margin_Y1__c = 5,
            Partner_Billing_Type__c = 'Direct',
            Client__c = acctId,
            Partner_Tier__c = 'Gold'
        );
        insert testPartnerMargin;
        return testPartnerMargin;
    }

    public static Partner_Tier__c createPartnerTier(Id partnerId) {
        Partner_Tier__c tier = new Partner_Tier__c();
        tier.Partner__c = partnerId;
        tier.PartnerTier_Status__c = 'Active';
        tier.Partner_Tier__c = 'Gold';
        tier.Partner_Tier_Start_Date__c = System.today();
        insert tier;
        return tier;
    }    

    public static Partner_Client_Relationship__c createPartnerClientRelationship(Id partnerId, Id clientId) {
        Partner_Client_Relationship__c rel = new Partner_Client_Relationship__c();
        rel.Partner__c = partnerId;
        rel.Client__c = clientId;
        rel.Partner_Client_Margin_Eligibility__c = 'Active';
        rel.Margin_Start_Date__c = System.today();
        rel.Partner_of_Record_Status__c = 'Current';
        insert rel;
        return rel;
    }
    
}