force-app/main/default/objects/Account/fields/Active_Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Active_Partner_Tier__c</fullName>
    <label>Active Partner Tier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARR_MFC__c.field-meta.xml
<CustomField>
    <fullName>ARR_MFC__c</fullName>
    <formula>MRR_ROLL_UP__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR (Account)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_through_Partner__c.field-meta.xml
<CustomField>
    <fullName>Bill_through_Partner__c</fullName>
    <defaultValue>&quot;Direct&quot;</defaultValue>
    <label>Default Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill through Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Derived from Assigned Partner picklist</description>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Level__c.field-meta.xml
<CustomField>
    <fullName>Partner_Level__c</fullName>
    <label>Economic Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold Plus</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feature_Activation__c/Feature_Activation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Determines whether certain features are enabled or disabled.</description>
    <label>Feature Activation</label>
</CustomObject>

force-app/main/default/objects/Feature_Activation__c/fields/Default_Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Pricebook_Id__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Determines whether the Opportunity Pricebook Id should be defaulted based on the Account&apos;s Partner Level.</inlineHelpText>
    <label>Default Pricebook Id</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Manual_Discount__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Manual_Discount__c</fullName>
    <label>Manual Discount</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Subscription_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Id</label>
    <referenceTo>chargebeeapps__CB_Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enhancement_ARR_Opp_MFC__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_ARR_Opp_MFC__c</fullName>
    <defaultValue>00.00</defaultValue>
    <label>Enhancement ARR (Opp)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <description>If Net ARR is populated, this field equals Net ARR. Otherwise, it is a rep&apos;s estimation.</description>
    <label>Estimated Value ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Manual_Discount__c.field-meta.xml
<CustomField>
    <fullName>Manual_Discount__c</fullName>
    <label>Manual Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Manual_Discount_Fixed__c.field-meta.xml
<CustomField>
    <fullName>Manual_Discount_Fixed__c</fullName>
    <label>Manual Discount Fixed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Identify the partner involved in this deal.  If this is a direct deal, leave this blank</inlineHelpText>
    <label>Partner for Margin</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunities</relationshipLabel>
    <relationshipName>OpportunitiesPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Perpetual_Total_Opp_Billing_MFC__c.field-meta.xml
<CustomField>
    <fullName>Perpetual_Total_Opp_Billing_MFC__c</fullName>
    <defaultValue>00.00</defaultValue>
    <label>Perpetual Billing (Opp)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_ARR_MFC1__c.field-meta.xml
<CustomField>
    <fullName>Sales_ARR_MFC1__c</fullName>
    <label>Gross ARR (Opp)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subscription_ARR_Opp_MFC__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ARR_Opp_MFC__c</fullName>
    <defaultValue>00.00</defaultValue>
    <label>Subscription ARR (Opp)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subscription_Total_Opp_Billing_MFC__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Total_Opp_Billing_MFC__c</fullName>
    <defaultValue>00.00</defaultValue>
    <label>Subscription Billing (Opp)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_ARR_Opp__c.field-meta.xml
<CustomField>
    <fullName>Total_ARR_Opp__c</fullName>
    <label>Total ARR (Opp)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Year_One__c.field-meta.xml
<CustomField>
    <fullName>Year_One__c</fullName>
    <label>Year One</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Year_Three__c.field-meta.xml
<CustomField>
    <fullName>Year_Three__c</fullName>
    <label>Year Three</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Year_Two__c.field-meta.xml
<CustomField>
    <fullName>Year_Two__c</fullName>
    <label>Year Two</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/New_Business.recordType-meta.xml
<RecordType>
    <fullName>New_Business</fullName>
    <active>true</active>
    <businessProcess>New Business</businessProcess>
    <description>Use this for all standard opportunities for new and existing business</description>
    <label>New Business</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Renewals</businessProcess>
    <description>Renewal Opportunities</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/ARR_MFC__c.field-meta.xml
<CustomField>
    <fullName>ARR_MFC__c</fullName>
    <formula>Sales_ARR_MFC__c  * ( 1 -  Customer_Discount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR (Opp Product)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Licensing__c.field-meta.xml
<CustomField>
    <fullName>Licensing__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Licensing__c)</formula>
    <label>Licensing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Opportunity.Partner__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Perpetual_Type__c.field-meta.xml
<CustomField>
    <fullName>Perpetual_Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Perpetual_Type__c)</formula>
    <label>Perpetual Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Revenue__c</fullName>
    <formula>PricebookEntry.Product2.Recurring_Revenue__c</formula>
    <label>Recurring Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Subscription_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Product_Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Subscription_Product_Type2__c)</formula>
    <label>Subscription Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/Partner_Margin__c.object-meta.xml
<CustomObject>
    <label>Partner Margin</label>
    <nameField>
        <label>Partner Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin__c/fields/CB_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>CB_Subscription_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CB Subscription ID</label>
    <referenceTo>chargebeeapps__CB_Subscription__c</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins (Partner)</relationshipLabel>
    <relationshipName>Partner_Margins2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
//Trigger Handler for Opportunity Line Item
// 2017-12-21 Ray Dehler <rdehler@square2marketing.com> created
public with sharing class OpportunityTriggerHandler {   
    public static Feature_Activation__c fa = Feature_Activation__c.getInstance();

   
    public static void onBeforeInsert(List<Opportunity> newList) {
        defaultPricebookId(newList);
        calculateRenewalEstimatedValue(newList);
    }
    
    public static void onBeforeUpdate(List<Opportunity> newList, Map<Id, Opportunity> oldMap) {
        updateManualDiscount(newList, oldMap);
        calculateRenewalEstimatedValue(newList);
    }
   
    public static void afterUpdate(Map<Id,Opportunity> newOppMap, Map<Id,Opportunity> oldOppMap) {
        List<Opportunity> oppList = new List<Opportunity>();
        Set<Id> oppIdSet = new Set<Id>();
        Set<Id> oppIdSetToUpdatePM = new Set<Id>();
        Boolean isReccuringRev = false;
        List<OpportunityLineItem> oppProductList = new List<OpportunityLineItem>();
        for(Opportunity opp: newOppMap.values()){
            if(oldOppMap != null && opp.Partner__c != oldOppMap.get(opp.Id).Partner__c && opp.Partner__c != null){
                oppIdSet.add(opp.Id);
            }
            if(oldOppMap != null && opp.chargebeeapps__Subscription_Id__c != oldOppMap.get(opp.Id).chargebeeapps__Subscription_Id__c && opp.chargebeeapps__Subscription_Id__c != null){
                oppIdSetToUpdatePM.add(opp.Id);
            }
        }
        if(oppIdSet != null && oppIdSet.size() > 0){
            oppList = [SELECT ID, Name,Partner__c,StageName,AccountId,Partner__r.Active_Partner_Tier__c,Partner__r.Bill_through_Partner__c,Sales_ARR_MFC1__c,Total_ARR_Opp__c,Subscription_ARR_Opp_MFC__c,Enhancement_ARR_Opp_MFC__c,
                       Subscription_Total_Opp_Billing_MFC__c,Perpetual_Total_Opp_Billing_MFC__c,chargebeeapps__Subscription_Id__c,
                       (Select ID,Name,OpportunityId,Quantity,Recurring_Revenue__c,TotalPrice,
                        Licensing__c,ARR_MFC__c,Perpetual_Type__c,Subscription_Product_Type__c,Product_Name__c,ProductCode 
                        From OpportunityLineItems)
                       FROM Opportunity
                       WHERE Id IN :oppIDSet];
            
            for(Opportunity opp: oppList){
                oppProductList.addAll(opp.OpportunityLineItems);
                for(OpportunityLineItem oppProd: opp.OpportunityLineItems){
                    if(oppProd.Recurring_Revenue__c){
                        isReccuringRev = true; 
                    } 
                }
            }
        }
        
        if(isReccuringRev && oppList != null && oppList.size() > 0 && oppProductList != null && oppProductList.size()>0){
            PartnerMarginService.createPartnerMargin(oppList,oppProductList);
        }
        
        if(oppIdSetToUpdatePM != null && oppIdSetToUpdatePM.size() > 0){
            List<Partner_Margin__c> oppRelatedPMList = [Select ID,CB_Subscription_ID__c,
                                                        Opportunity__r.chargebeeapps__Subscription_Id__c From 
                                                        Partner_Margin__c where Opportunity__c In:oppIdSetToUpdatePM ];
            if(oppRelatedPMList != null && oppRelatedPMList.size() > 0){
                for(Partner_Margin__c pm: oppRelatedPMList){
                   pm.CB_Subscription_ID__c = pm.Opportunity__r.chargebeeapps__Subscription_Id__c; 
                }
                update oppRelatedPMList;
            }
        }
    }
   
    /**
     * Calculates Estimated Value ARR for Renewal-type opportunities on the New Business record type.
     * Formula: MAX(0, (Subscription MRR * 12) - ((Year One + Year Two + Year Three) / 3))
     * The subscription MRR comes from the Chargebee subscription linked to the opportunity.
     */
    private static void calculateRenewalEstimatedValue(List<Opportunity> newList) {
        // Get New Business RecordType Id
        Id newBusinessRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
            .get('New_Business').getRecordTypeId();
        
        // Collect subscription IDs for Renewal-type New Business opportunities
        Map<Id, List<Opportunity>> subIdToOpps = new Map<Id, List<Opportunity>>();
        for (Opportunity opp : newList) {
            if (opp.RecordTypeId == newBusinessRecTypeId && 
                opp.Type == 'Renewal' && 
                opp.chargebeeapps__Subscription_Id__c != null &&
                (opp.Year_One__c != null || opp.Year_Two__c != null || opp.Year_Three__c != null)) {
                
                if (!subIdToOpps.containsKey(opp.chargebeeapps__Subscription_Id__c)) {
                    subIdToOpps.put(opp.chargebeeapps__Subscription_Id__c, new List<Opportunity>());
                }
                subIdToOpps.get(opp.chargebeeapps__Subscription_Id__c).add(opp);
            }
        }
        
        if (subIdToOpps.isEmpty()) {
            return;
        }
        
        // Query subscription MRR values
        Map<Id, Decimal> subIdToMrr = new Map<Id, Decimal>();
        for (chargebeeapps__CB_Subscription__c sub : [
            SELECT Id, chargebeeapps__MRR__c 
            FROM chargebeeapps__CB_Subscription__c 
            WHERE Id IN :subIdToOpps.keySet()
        ]) {
            subIdToMrr.put(sub.Id, sub.chargebeeapps__MRR__c != null ? sub.chargebeeapps__MRR__c : 0);
        }
        
        // Calculate and set Estimated Value ARR
        for (Id subId : subIdToOpps.keySet()) {
            Decimal mrr = subIdToMrr.containsKey(subId) ? subIdToMrr.get(subId) : 0;
            Decimal subscriptionArr = mrr * 12;
            
            for (Opportunity opp : subIdToOpps.get(subId)) {
                Decimal yearOne = opp.Year_One__c != null ? opp.Year_One__c : 0;
                Decimal yearTwo = opp.Year_Two__c != null ? opp.Year_Two__c : 0;
                Decimal yearThree = opp.Year_Three__c != null ? opp.Year_Three__c : 0;
                
                Decimal average = (yearOne + yearTwo + yearThree) / 3;
                Decimal estimatedValue = subscriptionArr - average;
                
                // If negative, set to $0
                opp.Estimated_Value__c = estimatedValue < 0 ? 0 : estimatedValue;
            }
        }
    }
    
    private static void defaultPricebookId(List<Opportunity> newList) {
        if (!fa.Default_Pricebook_Id__c) {
            return;
        }
       
        Map<String, Pricebook2> pricebookMap = new Map<String, Pricebook2>();
        Id standardPbId;
        for (Pricebook2 pb : [select Id, Name, IsStandard from Pricebook2 where IsActive = true]) {
            pricebookMap.put(pb.Name, pb);
            if (pb.IsStandard) {
                standardPbId = pb.Id;
            }
        }

        Map<Id, Account> accountMap = new Map<Id, Account>();
        for (Opportunity opp : newList) {
            accountMap.put(opp.AccountId, null);
        }        
       
        accountMap = new Map<Id, Account>([select Partner_Level__c from Account where Id in :accountMap.keySet()]);
       
        for (Opportunity opp : newList) {
            if (opp.Pricebook2Id != null) {
                continue;
            }
            opp.Pricebook2Id = standardPbId;
        }
    }
    
    /**
     * Updates the Manual_Discount__c field based on the chargebeeapps__Manual_Discount__c JSON data
     */
    private static void updateManualDiscount(List<Opportunity> newList, Map<Id, Opportunity> oldMap) {
        for (Opportunity opp : newList) {
            Opportunity oldOpp = oldMap.get(opp.Id);
            
            // Check if the chargebeeapps__Manual_Discount__c field has changed
            if (opp.chargebeeapps__Manual_Discount__c != oldOpp.chargebeeapps__Manual_Discount__c && 
                opp.chargebeeapps__Manual_Discount__c != null) {
                
                try {
                    // Parse the JSON and extract the discount percentage
                    Decimal discountPercentage = parseManualDiscountPercentage(opp.chargebeeapps__Manual_Discount__c);
                    if (discountPercentage != null) {
                        opp.Manual_Discount__c = discountPercentage;
                    }
                    Decimal discountAmount = parseManualDiscountAmount(opp.chargebeeapps__Manual_Discount__c);
                    if (discountAmount != null) {
                        opp.Manual_Discount_Fixed__c = discountAmount;
                    }
                } catch (Exception e) {
                    System.debug('Error parsing manual discount JSON: ' + e.getMessage());
                    // Don't throw exception to avoid breaking the trigger
                }
            }
        }
    }
    
    /**
     * Parses the manual discount JSON string and extracts the discount percentage
     * Returns the first percentage discount found, or null if none found
     */
    private static Decimal parseManualDiscountPercentage(String jsonString) {
        try {
            List<QuoteLineDiscount> discounts = (List<QuoteLineDiscount>) JSON.deserialize(jsonString, List<QuoteLineDiscount>.class);
            
            for (QuoteLineDiscount discount : discounts) {
                // Look for percentage discounts that are invoice-level discounts
                if (discount.isPercentageDiscount != null && discount.isPercentageDiscount && 
                    discount.isInvoiceDiscount != null && discount.isInvoiceDiscount &&
                    String.isNotBlank(discount.discountPercentage)) {
                    
                    return Decimal.valueOf(discount.discountPercentage);
                }
            }
        } catch (Exception e) {
            System.debug('Error deserializing manual discount JSON: ' + e.getMessage());
        }
        
        return null;
    }

    private static Decimal parseManualDiscountAmount(String jsonString) {
        try {
            List<QuoteLineDiscount> discounts = (List<QuoteLineDiscount>) JSON.deserialize(jsonString, List<QuoteLineDiscount>.class);
            for (QuoteLineDiscount discount : discounts) {
                if (discount.isFixedDiscount != null && discount.isFixedDiscount && 
                    String.isNotBlank(discount.discountAmount)) {
                    return Decimal.valueOf(discount.discountAmount);
                }
            }
        } catch (Exception e) {
            System.debug('Error deserializing manual discount JSON: ' + e.getMessage());
        }
        return null;
    }
}