force-app/main/default/objects/Account/fields/ARR_MFC__c.field-meta.xml
<CustomField>
    <fullName>ARR_MFC__c</fullName>
    <formula>MRR_ROLL_UP__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR (Account)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_through_Partner__c.field-meta.xml
<CustomField>
    <fullName>Bill_through_Partner__c</fullName>
    <defaultValue>&quot;Direct&quot;</defaultValue>
    <label>Default Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill through Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Derived from Assigned Partner picklist</description>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Subscription_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Id</label>
    <referenceTo>chargebeeapps__CB_Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Identify the partner involved in this deal.  If this is a direct deal, leave this blank</inlineHelpText>
    <label>Partner for Margin</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunities</relationshipLabel>
    <relationshipName>OpportunitiesPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ARR_MFC__c.field-meta.xml
<CustomField>
    <fullName>ARR_MFC__c</fullName>
    <formula>Sales_ARR_MFC__c  * ( 1 -  Customer_Discount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR (Opp Product)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Licensing__c.field-meta.xml
<CustomField>
    <fullName>Licensing__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Licensing__c)</formula>
    <label>Licensing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Opportunity.Partner__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Perpetual_Type__c.field-meta.xml
<CustomField>
    <fullName>Perpetual_Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Perpetual_Type__c)</formula>
    <label>Perpetual Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Revenue__c</fullName>
    <formula>PricebookEntry.Product2.Recurring_Revenue__c</formula>
    <label>Recurring Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Subscription_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Product_Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Subscription_Product_Type2__c)</formula>
    <label>Subscription Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/Partner_Client_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner-Client Relationship</label>
    <nameField>
        <label>Partner-Client Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner-Client Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships</relationshipLabel>
    <relationshipName>Partner_Client_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Client_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/Partner_Margin__c.object-meta.xml
<CustomObject>
    <label>Partner Margin</label>
    <nameField>
        <label>Partner Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin__c/fields/CB_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>CB_Subscription_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CB Subscription ID</label>
    <referenceTo>chargebeeapps__CB_Subscription__c</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Enhancement_Partner_Margin_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Partner_Margin_Renewal__c</fullName>
    <label>Enhancement - Partner Margin % (Renewal)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins (Partner)</relationshipLabel>
    <relationshipName>Partner_Margins2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Billing_Type__c</fullName>
    <label>Partner Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill through Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Client_Margin_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Margin_Eligibility__c</fullName>
    <label>Partner-Client Margin Eligibility</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Margin_Duration__c.field-meta.xml
<CustomField>
    <fullName>Partner_Margin_Duration__c</fullName>
    <label>Partner Margin Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-time</fullName>
            </value>
            <value>
                <fullName>On-going</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold Plus</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Software_Partner_Margin_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Software_Partner_Margin_Renewal__c</fullName>
    <label>Software - Partner Margin % (Renewal)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Software_Partner_Margin_Y1__c.field-meta.xml
<CustomField>
    <fullName>Software_Partner_Margin_Y1__c</fullName>
    <label>Software - Partner Margin % (Y1)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/Partner_Tier__c.object-meta.xml
<CustomObject>
    <label>Partner Tier</label>
    <nameField>
        <label>Partner Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Tier__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Tiers</relationshipLabel>
    <relationshipName>Partner_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold Plus</fullName>
                <isActive>false</isActive>
                <label>Gold Plus</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Licensing__c.field-meta.xml
<CustomField>
    <fullName>Licensing__c</fullName>
    <label>Licensing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
                <default>true</default>
                <label>Subscription</label>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Perpetual_Type__c.field-meta.xml
<CustomField>
    <fullName>Perpetual_Type__c</fullName>
    <label>Perpetual Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Revenue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PartnerMarginService_Test.cls
@isTest
public class PartnerMarginService_Test {

    @testSetup
    static void setup() {
        Account partnerAccount1 = TestUtils.createPartnerAccount();
        partnerAccount1.Name = 'Test Partner Account 1';
        update partnerAccount1;

        Account partnerAccount2 = TestUtils.createPartnerAccount();
        partnerAccount2.Name = 'Test Partner Account 2';
        update partnerAccount2;

        Account clientAccount = TestUtils.createAccount();
        
        Opportunity opp1 = TestUtils.createOpportunity(clientAccount.Id, partnerAccount1.Id);
        Opportunity opp2 = TestUtils.createOpportunity(clientAccount.Id, partnerAccount2.Id);

        Partner_Tier__c partnerTier1 = TestUtils.createPartnerTier(partnerAccount1.Id);
        Partner_Tier__c partnerTier2 = TestUtils.createPartnerTier(partnerAccount2.Id);
        partnerTier2.Partner_Tier__c = 'Silver';
        update partnerTier2;

        Partner_Client_Relationship__c partnerClientRel1 = TestUtils.createPartnerClientRelationship(partnerAccount1.Id, clientAccount.Id);
        Partner_Client_Relationship__c partnerClientRel2 = TestUtils.createPartnerClientRelationship(partnerAccount2.Id, clientAccount.Id);
        partnerClientRel2.Partner_Client_Margin_Eligibility__c = 'Inactive';
        update partnerClientRel2;

        Product2 prod = TestUtils.createProduct('Test Product');
        PricebookEntry pbe = TestUtils.createPricebookEntry(opp1.Pricebook2Id, prod.Id, 100);
        TestUtils.createOpportunityLineItem(opp1.Id, pbe.Id);
        TestUtils.createOpportunityLineItem(opp2.Id, pbe.Id);
    }

    @isTest
    static void testCreatePartnerMargin() {
        List<Opportunity> oppList = [SELECT Id, AccountId, Partner__c, StageName, chargebeeapps__Subscription_Id__c, Partner__r.Bill_through_Partner__c FROM Opportunity];
        List<OpportunityLineItem> oppLineList = [SELECT Id, OpportunityId, Quantity, TotalPrice, Recurring_Revenue__c, Subscription_Product_Type__c, Licensing__c, Perpetual_Type__c, ARR_MFC__c, ProductCode, Product_Name__c FROM OpportunityLineItem];

        Test.startTest();
        PartnerMarginService.createPartnerMargin(oppList, oppLineList);
        Test.stopTest();
    }

    @isTest
    static void testDeletePartnerMargin() {
        List<Opportunity> oppList = [SELECT Id FROM Opportunity LIMIT 1];
        Set<Id> oppIdSet = new Set<Id>();
        for (Opportunity opp : oppList) {
            oppIdSet.add(opp.Id);
        }

        Test.startTest();
        PartnerMarginService.deletePartnerMargin(oppIdSet);
        Test.stopTest();
    }

    @isTest
    static void testUpdatePartnerForInactiveTiers() {
        List<Account> partnerAccounts = [SELECT Id FROM Account WHERE Type = 'Partner - Prospective' LIMIT 2];
        Set<Id> partnerAccountIds = new Set<Id>();
        for (Account acc : partnerAccounts) {
            partnerAccountIds.add(acc.Id);
        }

        Test.startTest();
        PartnerMarginService.updatePartnerForInactiveTiers(partnerAccountIds);
        Test.stopTest();
    }

    @isTest
    static void testClonePartnerMargin() {
        List<Partner_Margin__c> partnerMargins = [SELECT Id FROM Partner_Margin__c LIMIT 1];

        Test.startTest();
        List<Id> clonedPartnerMarginIds = PartnerMarginService.clonePartnerMargin(partnerMargins);
        Test.stopTest();
    }

    @isTest
    static void testMergePartnerMargin() {
        List<Partner_Margin__c> partnerMargins = [SELECT Id, CB_Subscription_ID__c, Client__c, Partner__c, Partner_Billing_Type__c, Partner_Tier__c, Partner_Margin_Duration__c, Software_Partner_Margin_Y1__c, Software_Partner_Margin_Renewal__c, Enhancement_Partner_Margin_Renewal__c FROM Partner_Margin__c LIMIT 2];

        if (partnerMargins.size() == 2) {
            Partner_Margin__c p1 = partnerMargins[0];
            Partner_Margin__c p2 = partnerMargins[1];

            Test.startTest();
            Partner_Margin__c mergedPM = PartnerMarginService.mergePartnerMargin(p1, p2);
            Test.stopTest();
        }
    }
}