force-app/main/default/objects/Account/fields/Billing_Method__c.field-meta.xml
<CustomField>
    <fullName>Billing_Method__c</fullName>
    <label>Billing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Time and Materials</fullName>
                <default>true</default>
                <label>Time and Materials</label>
            </value>
            <value>
                <fullName>Fixed-Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>populated from CB Invoice Line Item</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enhancement_Date__c.field-meta.xml
<CustomField>
    <fullName>Enhancement_Date__c</fullName>
    <label>Enhancement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Level__c.field-meta.xml
<CustomField>
    <fullName>Partner_Level__c</fullName>
    <label>Economic Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold Plus</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <inlineHelpText>Used on the Quote PDF under the &quot;Terms&quot; header</inlineHelpText>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Portal_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Portal_Account_ID__c</fullName>
    <description>Unique Account ID generated by the partner portal</description>
    <externalId>true</externalId>
    <label>Portal Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Method__c.field-meta.xml
<CustomField>
    <fullName>Billing_Method__c</fullName>
    <label>Billing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Time and Materials</fullName>
                <default>true</default>
                <label>Time and Materials</label>
            </value>
            <value>
                <fullName>Fixed Rate</fullName>
            </value>
            <value>
                <fullName>Not-To-Exceed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BSA__c.field-meta.xml
<CustomField>
    <fullName>BSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDEV Product Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <label>Customer PO</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <defaultValue>&quot;8 weeks&quot;</defaultValue>
    <label>Lead Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Times</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>This Opportunity should probably be related to a Standard Opportunity Type</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Reseller Opportunties</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>&quot;Net 15&quot;</defaultValue>
    <description>Being Deprecated for Intact field called Term</description>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Sales Engineer, Project Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__mdt/OpportunityLineItem__mdt.object-meta.xml
<CustomObject>
    <label>Exclude CB Plans Products</label>
    <pluralLabel>Exclude CB Plans Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__mdt/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Billing_Method__c.field-meta.xml
<CustomField>
    <fullName>Billing_Method__c</fullName>
    <label>Billing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Time and Materials</fullName>
                <default>true</default>
                <label>Time and Materials</label>
            </value>
            <value>
                <fullName>Fixed-Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/BSA__c.field-meta.xml
<CustomField>
    <fullName>BSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDEV Product Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Contract_Terms__c.field-meta.xml
<CustomField>
    <fullName>Contract_Terms__c</fullName>
    <formula>Contract_End_Date__c -  Contract_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Terms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Custom_Discount_Work_Description_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Custom_Discount_Work_Description_Rollup__c</fullName>
    <label>Custom Discount Work Description Rollup</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Discount_Price__c.field-meta.xml
<CustomField>
    <fullName>Discount_Price__c</fullName>
    <label>Discount Price</label>
    <summarizedField>QuoteLineItem.UnitPrice</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Product_Code_rollup__c</field>
        <operation>equals</operation>
        <value>CST00011</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Discount_Years__c.field-meta.xml
<CustomField>
    <fullName>Discount_Years__c</fullName>
    <label>Discount Years</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Year</fullName>
                <default>true</default>
                <label>1 Year</label>
            </value>
            <value>
                <fullName>2 Years</fullName>
            </value>
            <value>
                <fullName>3 Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <inlineHelpText>Used as the &quot;Lead Time&quot; field on the top of the Quote</inlineHelpText>
    <label>Lead Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Continuation of Project</fullName>
            </value>
            <value>
                <fullName>1-2 Days</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
                <label>2 Weeks</label>
            </value>
            <value>
                <fullName>4 weeks</fullName>
                <label>4 Weeks</label>
            </value>
            <value>
                <fullName>6 weeks</fullName>
                <label>6 Weeks</label>
            </value>
            <value>
                <fullName>8 weeks</fullName>
                <label>8 Weeks</label>
            </value>
            <value>
                <fullName>10 weeks</fullName>
                <label>10 Weeks</label>
            </value>
            <value>
                <fullName>12 weeks</fullName>
                <label>12 Weeks</label>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
                <label>16 Weeks</label>
            </value>
            <value>
                <fullName>18 weeks</fullName>
            </value>
            <value>
                <fullName>20 weeks</fullName>
                <label>20 Weeks</label>
            </value>
            <value>
                <fullName>22 Weeks</fullName>
            </value>
            <value>
                <fullName>24 Weeks</fullName>
                <label>24 weeks</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Number_of_Quotes_Generated__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Quotes_Generated__c</fullName>
    <inlineHelpText>Determines the V number on the next quote generated.  It will be this number + 1. You do not need to manually edit this field.</inlineHelpText>
    <label>Number of Quotes Generated</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <formula>Opportunity.Payment_Terms__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SoW_Version__c.field-meta.xml
<CustomField>
    <fullName>SoW_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <label>SoW Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Term_Length__c.field-meta.xml
<CustomField>
    <fullName>Term_Length__c</fullName>
    <label>Term Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Prorated_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Prorated_Price__c</fullName>
    <label>Total Prorated Price</label>
    <summarizedField>QuoteLineItem.Prorated_Price__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLinesForPDF__mdt/QuoteLinesForPDF__mdt.object-meta.xml
<CustomObject>
    <label>QuoteLinesForPDF</label>
    <pluralLabel>QuoteLinesForPDFs</pluralLabel>
</CustomObject>

force-app/main/default/objects/QuoteLinesForPDF__mdt/fields/QuoteLineId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineId__c</fullName>
    <label>QuoteLineId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Times.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2 Days</fullName>
    </customValue>
    <customValue>
        <fullName>2 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>3 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>5 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>6 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>7 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>9 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>10 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>14 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>18 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>20 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>24 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>28 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>22 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Continuation of Project</fullName>
    </customValue>
    <masterLabel>Lead Times</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CavalloBudgetaryEstimateController.cls
public without sharing class CavalloBudgetaryEstimateController {
   
    public Quote q {get; set;}
    private Id quoteId;
    public String today {
        get {   
            return Date.today().format();
        }
    }
    public String renderAs {
        get {
            if (!ApexPages.currentPage().getParameters().containsKey('renderAs')) {
                return 'pdf';
            } else {
                return ApexPages.currentPage().getParameters().get('renderAs');
            }
        }
    }
    public Map<String, QuoteLinesForPDF__mdt> mapQuoteLines {get; set;}
    public Map<String, OpportunityLineItem__mdt> mapQuoteLines1 {get; set;}

    @testVisible public Map<Id, String> quoteLineProductsTobeConsidered {
        get {
            if (quoteLineProductsTobeConsidered == null) {
                //fetch metadata to prepare map of products to be considerd 
                mapQuoteLines = QuoteLinesForPDF__mdt.getAll();
                quoteLineProductsTobeConsidered = new Map<Id, String>();
                for(String quoteLineDetail : mapQuoteLines.keySet()){
                    quoteLineProductsTobeConsidered.put((Id)mapQuoteLines.get(quoteLineDetail).QuoteLineId__c, quoteLineDetail);
                }
            }
            return quoteLineProductsTobeConsidered;
        }
        set;
    }

    @testVisible public Set<Id> quoteLineItemsToBeSkipped {
        get {
            if (quoteLineItemsToBeSkipped == null) {
                //fetch metadata to prepare set of line items not to be considerd 
                mapQuoteLines1 = OpportunityLineItem__mdt.getAll();
                quoteLineItemsToBeSkipped = new Set<Id> ();
                for(String quoteLines : mapQuoteLines1.keySet()){
                    quoteLineItemsToBeSkipped.add(mapQuoteLines1.get(quoteLines).Product_ID__c);
                }
            }
            return quoteLineItemsToBeSkipped;
        }
        set;
    }
    
    
    
    public CavalloBudgetaryEstimateController(ApexPages.StandardController sc) {
        try {
            quoteId = sc.getId();

           q = [select Id, QuoteNumber, Name, Lead_Time__c, TotalPrice, ExpirationDate, Contract_Start_Date__c,Discount_Price__c,
                        SOW_VERSION__c,BillingStreet,BillingCity,BillingState,BillingPostalCode,Custom_Discount_Work_Description_Rollup__c,
                        Contract_End_Date__c, Contract_Terms__c, Term_Length__c, Discount_Years__c,Total_Prorated_Price__c,Billing_Method__c,
                        Contact.Name,Description,
                        Account.Name, Account.BillingStreet,
                        Account.BillingCity, Account.BillingState,
                        Account.BillingPostalCode, Account.BillingCountry,Account.Owner.Name,Account.Owner.Email,
                        Account.Portal_Account_Id__c, Account.Partner_level__c, Opportunity.Parent_Opportunity__c, Opportunity.Parent_Opportunity__r.Account.Enhancement_Date__c, Opportunity.RecordTypeId, Account.Enhancement_Date__c, Opportunity.Payment_Terms__c,
                        Opportunity.Name,Opportunity.Owner.Name, Opportunity.Sales_Engineer__r.Name,
                        Opportunity.RecordType.Name, Number_of_Quotes_Generated__c, opportunity.Type,Opportunity.BSA__r.Name,Opportunity.Customer_PO__c,
                    (select PricebookEntry.Product2.Name,Product2.Name,Product2.Family,Product2Id, Quantity, UnitPrice, discount,Product2.Description, Custom_Product_Type_Label__c,
                            TotalPrice,ListPrice, Comments__c, Prorated_Price__c,Custom_Product_Type__c,Work_Description__c,Description
                     from QuoteLineItems WHERE Product2Id NOT IN :quoteLineItemsToBeSkipped
                     order by SortOrder ASC,LineNumber ASC nulls last)
                 from Quote
                 where Id = :quoteId];
        }
        catch(Exception e) {
            ApexPages.addMessages(e);
        }
    }
  
    public PageReference saveAndOpenPDF() {
        if (String.isBlank(ApexPages.currentPage().getParameters().get('displayOnly'))) {
            Id attachmentId = savePDF();
            if(test.isrunningtest()){
                return openPDF(attachmentId);
            }
           // return openPDF(attachmentId);
           return null;
        } else {
            return null;
        }
    }
    
    public Id savePDF() {
        Attachment attachment = new Attachment();
        attachment.ParentId = quoteId;
        Integer versionNumber = getVersionNumber()+1;
        attachment.name = 'Quote for ' + q.Opportunity.Name +'-'+ Date.today().month()+'_'+ Date.today().day() + '_' + Date.today().year()+'.pdf';

        PageReference pdf = Page.CavalloBudgetaryEstimatePDF;
        pdf.getParameters().put('Id', quoteId);
        pdf.getParameters().put('displayOnly', '1');
        pdf.setRedirect(true);
        try {
            attachment.Body = pdf.getContent();
        }
        catch (VisualForceException e) {
            attachment.Body = Blob.valueof('There was an error.');
        }
        attachment.ContentType = 'application/pdf';
        insert attachment;

        return attachment.Id;
    }
    
   
    private Integer getVersionNumber() {
        return q.Number_of_Quotes_Generated__c  == null ? 0 : Integer.valueOf(q.Number_of_Quotes_Generated__c);
    }
    
    public PageReference openPDF(Id attachmentId) {
        PageReference ret = new PageReference('/servlet/servlet.FileDownload?file=' + attachmentId);
        ret.setRedirect(true);
        return ret;
    }

}