force-app/main/default/objects/Account/fields/Customer_Class__c.field-meta.xml
<CustomField>
    <fullName>Customer_Class__c</fullName>
    <inlineHelpText>Original customer class - taken from ERP</inlineHelpText>
    <label>Customer Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End User Cloud</fullName>
            </value>
            <value>
                <fullName>End User Desktop</fullName>
            </value>
            <value>
                <fullName>Ex end user Cloud</fullName>
            </value>
            <value>
                <fullName>Ex end user Desktop</fullName>
            </value>
            <value>
                <fullName>ISV</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ex Partner</fullName>
            </value>
            <value>
                <fullName>National Partner</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
                <isActive>false</isActive>
                <label>Dead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Direct_v_Partner__c.field-meta.xml
<CustomField>
    <fullName>Direct_v_Partner__c</fullName>
    <inlineHelpText>Is this being sold through a partner, or directly to the end user?</inlineHelpText>
    <label>Direct v Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existing_GP_or_New_GP__c.field-meta.xml
<CustomField>
    <fullName>Existing_GP_or_New_GP__c</fullName>
    <inlineHelpText>Does the person you&apos;re selling this to already own Dynamics GP, or will they also be purchasing Dynamics GP?</inlineHelpText>
    <label>Existing GP or New GP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing GP</fullName>
            </value>
            <value>
                <fullName>New GP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source_Global__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source_Global__c</fullName>
    <label>Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_SubSource_Global__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_SubSource_Global__c</fullName>
    <label>Opportunity Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Source_Global__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Subsource</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Sales Engineer, Project Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Cavallo</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA)-INS | salespadllcdbacavallosolutions1644863490847.cavallo_profit_scan</fullName>
    </customValue>
    <customValue>
        <fullName>PMP AA</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA) - INS</fullName>
        <isActive>false</isActive>
        <label>AppSource (SPZA) - INS</label>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Subsource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ABM</fullName>
    </customValue>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Applied AI for Distributors</fullName>
    </customValue>
    <customValue>
        <fullName>Blog</fullName>
    </customValue>
    <customValue>
        <fullName>BPR</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Cavallo Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Change Order</fullName>
    </customValue>
    <customValue>
        <fullName>Cliently</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Accumatica</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - acuConnect</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - AM Expo 2025</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - CSNA</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Directions EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Directions NA</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - DUG</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - GPUC</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Innovia</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Stoneridge</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Summit</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - TM Group</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - User</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Velosio ASPIRE</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - WennSoft Synergy</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Request</fullName>
    </customValue>
    <customValue>
        <fullName>Digital ads (Google, Bing)</fullName>
    </customValue>
    <customValue>
        <fullName>DSG Webinars</fullName>
    </customValue>
    <customValue>
        <fullName>DUG Forums</fullName>
    </customValue>
    <masterLabel>Lead Subsource</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CavalloBudgetaryEstimateController_Test.cls
@isTest
private class CavalloBudgetaryEstimateController_Test {
    static testMethod void testQuotePDF() {
        Account a = new Account(Name = 'Ray Test',Type = 'Other', Customer_Class__c = 'Other');
        insert a;
        
        Opportunity opp = new Opportunity(AccountId = a.Id);
        opp.Name = 'Ray Test';
        opp.CloseDate = Date.today();
        opp.StageName = 'Sandbox';
        opp.Direct_v_Partner__c = 'Partner';
        opp.Existing_GP_or_New_GP__c = 'Existing GP';
        opp.Opportunity_SubSource_Global__c = 'Blog';
        opp.Opportunity_Source_Global__c = 'Marketing';
        //opp.Sales_Engineer__c = '0056A000002zXKeQAM';
        insert opp;
        
        Quote q = new Quote(OpportunityId = opp.Id);
        q.Name = 'Ray Test';
        insert q;
        
		Test.startTest();
        ApexPages.currentPage().getParameters().put('Id', q.Id);
        CavalloBudgetaryEstimateController con = new CavalloBudgetaryEstimateController(new ApexPages.StandardController(q));
        System.assertEquals('pdf', con.renderAs);
        System.assertEquals(Date.today().format(), con.today);
        con.saveAndOpenPDF();
    }
}