force-app/main/default/objects/Account/fields/Customer_Class__c.field-meta.xml
<CustomField>
    <fullName>Customer_Class__c</fullName>
    <inlineHelpText>Original customer class - taken from ERP</inlineHelpText>
    <label>Customer Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End User Cloud</fullName>
            </value>
            <value>
                <fullName>End User Desktop</fullName>
            </value>
            <value>
                <fullName>Ex end user Cloud</fullName>
            </value>
            <value>
                <fullName>Ex end user Desktop</fullName>
            </value>
            <value>
                <fullName>ISV</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ex Partner</fullName>
            </value>
            <value>
                <fullName>National Partner</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
                <isActive>false</isActive>
                <label>Dead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Direct_v_Partner__c.field-meta.xml
<CustomField>
    <fullName>Direct_v_Partner__c</fullName>
    <inlineHelpText>Is this being sold through a partner, or directly to the end user?</inlineHelpText>
    <label>Direct v Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existing_GP_or_New_GP__c.field-meta.xml
<CustomField>
    <fullName>Existing_GP_or_New_GP__c</fullName>
    <inlineHelpText>Does the person you&apos;re selling this to already own Dynamics GP, or will they also be purchasing Dynamics GP?</inlineHelpText>
    <label>Existing GP or New GP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing GP</fullName>
            </value>
            <value>
                <fullName>New GP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityLineItemFamilyUpdate_Test.cls
@isTest
public class OpportunityLineItemFamilyUpdate_Test {
    @isTest
	static void testAddEnhancementItem() {
                
        Account a = new Account(Name = 'Ray test', Type = 'Other', Customer_Class__c = 'Other');
        insert a;
        
        Opportunity opp = new Opportunity(AccountId = a.Id,
                                          CloseDate = Date.today(),
                                          StageName = 'Sandbox',
                                          Name = 'Ray Test',
                                          Direct_v_Partner__c = 'Partner',
                                          Existing_GP_or_New_GP__c = 'Existing GP'
                                         
                                         );
        insert opp;
        
        Product2 prod1 = new Product2(Name = 'Ray Test',ProductCode='Product abc');
        Product2 prod2 = new Product2(Name = 'Ray Test Enhancement',ProductCode='Product ab1c');
        insert new List<Product2> {prod1, prod2};
            
        PricebookEntry pbe1 = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(),
                                                 Product2Id = prod1.Id,
                                                 UnitPrice = 1,
                                                 IsActive = true);
        PricebookEntry pbe2 = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(),
                                                 Product2Id = prod2.Id,
                                                 UnitPrice = 1,
                                                 IsActive = true);
        insert new List<PricebookEntry> {pbe1, pbe2};
            
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                          PricebookEntryId = pbe1.Id,
                                                          Quantity = 1,
                                                          UnitPrice = 1);
        Test.startTest();
        insert oli;
        Test.stopTest();
        
        //System.assertEquals(2, [select count() from OpportunityLineItem where OpportunityId = :opp.Id]);
    }
}