force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Derived from Assigned Partner picklist</description>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Reseller.recordType-meta.xml
<RecordType>
    <fullName>Reseller</fullName>
    <active>false</active>
    <description>A Reseller/VAR</description>
    <label>Reseller</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Reseller_Partner.recordType-meta.xml
<RecordType>
    <fullName>Reseller_Partner</fullName>
    <active>true</active>
    <label>Reseller Partner</label>
</RecordType>

force-app/main/default/objects/Partner_Tier__c/Partner_Tier__c.object-meta.xml
<CustomObject>
    <label>Partner Tier</label>
    <nameField>
        <label>Partner Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Tier__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Tiers</relationshipLabel>
    <relationshipName>Partner_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier__c</fullName>
    <label>Partner Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold Plus</fullName>
                <isActive>false</isActive>
                <label>Gold Plus</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier_End_Date__c</fullName>
    <label>Partner Tier End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier_End_Reasoning__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier_End_Reasoning__c</fullName>
    <label>Partner Tier End Reasoning</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Tier__c/fields/Partner_Tier_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tier_Start_Date__c</fullName>
    <label>Partner Tier Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PartnerTierTriggerHandler_Tests.cls
@isTest
private class PartnerTierTriggerHandler_Tests {
    
    @IsTest(SeeAllData=true)
    static void testPartnerTier() {
        RecordType acctPartnerResellerRecordType = [Select ID,DeveloperName From RecordType where DeveloperName='Reseller_Partner' limit 1];
        Account partnerAcct = new Account();
        partnerAcct.Name = 'Partner Account 1';
        partnerAcct.Type = 'Partner - Reseller';
        partnerAcct.RecordType = acctPartnerResellerRecordType;
        insert partnerAcct;
        
        Account partnerAcct2 = new Account();
        partnerAcct2.Name = 'Partner Account 2';
        partnerAcct2.Type = 'Partner - Reseller';
        partnerAcct2.RecordType = acctPartnerResellerRecordType;
        insert partnerAcct2;
        
        Partner_Tier__c pt = new Partner_Tier__c();
        pt.Name = 'Test';
        pt.Partner__c = partnerAcct.Id;
        pt.Partner_Tier_Start_Date__c = Date.Today();
        pt.Partner_Tier__c = 'Silver';
        
        test.startTest();
        insert pt;
        pt.Partner__c = partnerAcct2.Id;
        update pt;
        pt.Partner_Tier_End_Date__c = Date.Today()-1;
        pt.Partner_Tier_End_Reasoning__c = 'Testing';
        update pt;
        test.stopTest();
    }

}