force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <inlineHelpText>Used on the Quote PDF under the &quot;Terms&quot; header</inlineHelpText>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Portal_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Portal_Account_ID__c</fullName>
    <description>Unique Account ID generated by the partner portal</description>
    <externalId>true</externalId>
    <label>Portal Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/chargebeeapps__Manual_Discount__c.field-meta.xml
<CustomField>
    <fullName>chargebeeapps__Manual_Discount__c</fullName>
    <label>Manual Discount</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <defaultValue>&quot;8 weeks&quot;</defaultValue>
    <label>Lead Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Times</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>&quot;Net 15&quot;</defaultValue>
    <description>Being Deprecated for Intact field called Term</description>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <businessProcess>Custom</businessProcess>
    <label>Custom</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem__mdt/OpportunityLineItem__mdt.object-meta.xml
<CustomObject>
    <label>Exclude CB Plans Products</label>
    <pluralLabel>Exclude CB Plans Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__mdt/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GP</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Custom Development</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Consulting_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Subtotal__c</fullName>
    <label>Consulting Subtotal</label>
    <summarizedField>QuoteLineItem.Extended_Price__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Product_Code_rollup__c</field>
        <operation>contains</operation>
        <value>SRV00001</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Discount_Price__c.field-meta.xml
<CustomField>
    <fullName>Discount_Price__c</fullName>
    <label>Discount Price</label>
    <summarizedField>QuoteLineItem.UnitPrice</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Product_Code_rollup__c</field>
        <operation>equals</operation>
        <value>CST00011</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <inlineHelpText>Used as the &quot;Lead Time&quot; field on the top of the Quote</inlineHelpText>
    <label>Lead Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Continuation of Project</fullName>
            </value>
            <value>
                <fullName>1-2 Days</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
                <label>2 Weeks</label>
            </value>
            <value>
                <fullName>4 weeks</fullName>
                <label>4 Weeks</label>
            </value>
            <value>
                <fullName>6 weeks</fullName>
                <label>6 Weeks</label>
            </value>
            <value>
                <fullName>8 weeks</fullName>
                <label>8 Weeks</label>
            </value>
            <value>
                <fullName>10 weeks</fullName>
                <label>10 Weeks</label>
            </value>
            <value>
                <fullName>12 weeks</fullName>
                <label>12 Weeks</label>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
                <label>16 Weeks</label>
            </value>
            <value>
                <fullName>18 weeks</fullName>
            </value>
            <value>
                <fullName>20 weeks</fullName>
                <label>20 Weeks</label>
            </value>
            <value>
                <fullName>22 Weeks</fullName>
            </value>
            <value>
                <fullName>24 Weeks</fullName>
                <label>24 weeks</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Number_of_Quotes_Generated__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Quotes_Generated__c</fullName>
    <inlineHelpText>Determines the V number on the next quote generated.  It will be this number + 1. You do not need to manually edit this field.</inlineHelpText>
    <label>Number of Quotes Generated</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <formula>Opportunity.Payment_Terms__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Software_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Software_Subtotal__c</fullName>
    <label>Software Subtotal</label>
    <summarizedField>QuoteLineItem.Extended_Price__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Product_Code_rollup__c</field>
        <operation>notContain</operation>
        <value>SRV00001</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Price__c</fullName>
    <label>Total Sales Price</label>
    <summarizedField>QuoteLineItem.Extended_Price__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Service_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Service_Discount__c</fullName>
    <label>Total Service Discount</label>
    <summarizedField>QuoteLineItem.Discount_price__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Business_Line__c</field>
        <operation>equals</operation>
        <value>Professional Services</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Service_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Service_Sales_Price__c</fullName>
    <label>Total Service Sales Price</label>
    <summarizedField>QuoteLineItem.Extended_Price__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Business_Line__c</field>
        <operation>equals</operation>
        <value>Professional Services</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Service_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Total_Service_Subtotal__c</fullName>
    <formula>Total_Service_Sales_Price__c + Total_Service_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Service Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Software_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Software_Discount__c</fullName>
    <label>Total Software Discount</label>
    <summarizedField>QuoteLineItem.Discount_price__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Business_Line__c</field>
        <operation>equals</operation>
        <value>BC,GP</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Software_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Software_Sales_Price__c</fullName>
    <label>Total Software Sales Price</label>
    <summarizedField>QuoteLineItem.Extended_Price__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Business_Line__c</field>
        <operation>equals</operation>
        <value>BC,GP</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Software_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Total_Software_Subtotal__c</fullName>
    <formula>Total_Software_Sales_Price__c + Total_Software_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Software Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <description>Quote for Custom Development Services</description>
    <label>Custom</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <label>Business Line</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Line specific comments</description>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discount_price__c.field-meta.xml
<CustomField>
    <fullName>Discount_price__c</fullName>
    <formula>Discount  * UnitPrice  *  Quantity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discounted_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Sales_Price__c</fullName>
    <formula>ROUND(Sales_Enhanced_Discount_Price__c - (Sales_Enhanced_Discount_Price__c  * Discount ),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discounted Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Extended_Price__c.field-meta.xml
<CustomField>
    <fullName>Extended_Price__c</fullName>
    <formula>Discounted_Sales_Price__c *  Quantity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Extended Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <inlineHelpText>Order in which the Line will display on the Quote PDF</inlineHelpText>
    <label>Line Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Times.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2 Days</fullName>
    </customValue>
    <customValue>
        <fullName>2 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>3 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>5 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>6 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>7 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>9 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>10 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>14 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>18 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>20 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>24 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>28 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>22 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Continuation of Project</fullName>
    </customValue>
    <masterLabel>Lead Times</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotePDFController.cls
// Controller for the custom Quote PDF generation
// 2018-01-13 Ray Dehler <rdehler@square2marketing.com> created
public with sharing class QuotePDFController {
    public Quote q {get; set;}
    public List<QuoteLineDiscount> lineDiscountList {get; set;}
    private Id quoteId;
    public String totalSoftwareSP {get; set;}
    public String totalSoftwareDiscount {get; set;}
    public String totalSoftwareSubtotal {get; set;}
    public String totalServiceSP {get; set;}
    public String totalServiceDiscount {get; set;}
    public String totalServiceSubtotal {get; set;}
    // public Double doubleTotalServiceSP {get; set;}
    // public Double doubleTotalServiceDiscount {get; set;}
    // public Double doubleSubTotalService {get; set;}
    // public Double doubleTotalSoftwareSP {get; set;}
    // public Double doubleTotalSoftwareDiscount {get; set;}
    // public Double doubleSubTotalSoftware {get; set;}
    
    public String today {
        get {
            return Date.today().format();
        }
    }
    public Map<String, OpportunityLineItem__mdt> mapQuoteLines1 {get; set;}
    public List<chargebeeapps__CB_Opportunity_Coupon__c> chargebeeProds {get; set;}
    Set<String> waterMarkSet = new Set<String>{'Draft','Needs Review','In Review','Rejected'};
        @testVisible public Set<Id> quoteLineItemsToBeSkipped {
            get {
                if (quoteLineItemsToBeSkipped == null) {
                    //fetch metadata to prepare set of line items not to be considerd 
                    mapQuoteLines1 = OpportunityLineItem__mdt.getAll();
                    quoteLineItemsToBeSkipped = new Set<Id> ();
                    for(String quoteLines : mapQuoteLines1.keySet()){
                        quoteLineItemsToBeSkipped.add(mapQuoteLines1.get(quoteLines).Product_ID__c);
                    }
                }
                return quoteLineItemsToBeSkipped;
            }
            set;
        }
    
    public String renderAs {
        get {
            if (!ApexPages.currentPage().getParameters().containsKey('renderAs')) {
                return 'pdf';
            } else {
                return ApexPages.currentPage().getParameters().get('renderAs');
            }
        }
    }
    
    public QuotePDFController(ApexPages.StandardController sc) {
        try {
            String businessLineProfessionalServices = System.Label.OppLine_BusinessLine_ProfessionalServices;
            quoteId = sc.getId();
            q = [
                SELECT 
                    Id, QuoteNumber, Name, Status, Discount, Lead_Time__c, TotalPrice, ExpirationDate, Total_Sales_Price__c,
                    Contact.Name, Account.Name, Account.BillingStreet, Account.BillingCity, Account.BillingState,
                    Account.BillingPostalCode, Account.BillingCountry, Account.Portal_Account_Id__c, Opportunity.Payment_Terms__c,
                    Opportunity.Owner.Name,Opportunity.chargebeeapps__Manual_Discount__c, Opportunity.RecordType.Name, 
                    Number_of_Quotes_Generated__c, Software_Subtotal__c, Consulting_Subtotal__c, Payment_Terms__c,
                    Total_Service_Discount__c, Total_Service_Sales_Price__c, Total_Service_Subtotal__c, Total_Software_Discount__c,
                    Total_Software_Sales_Price__c, Total_Software_Subtotal__c,
                    (
                        SELECT 
                            PricebookEntry.Product2.Name, PricebookEntry.Product2.ProductCode, PricebookEntry.Product2.Business_Line__c, 
                            Quantity, Discount, UnitPrice, Product2Id, TotalPrice, Comments__c, Discount_price__c, 
                            Discounted_Sales_Price__c, Extended_Price__c 
                        FROM QuoteLineItems 
                        WHERE Product2Id 
                        NOT IN :quoteLineItemsToBeSkipped
                        ORDER BY Line_Number__c nulls last, LineNumber
                    )
                FROM Quote
                WHERE Id = :quoteId
            ];
            lineDiscountList = QuoteTriggerHandler.getManualDiscount(q.Opportunity.chargebeeapps__Manual_Discount__c);
            chargebeeProds = [
                SELECT Id, Name,  chargebeeapps__CB_Coupon__c, chargebeeapps__CB_Coupon__r.Name, Discount__c 
                FROM chargebeeapps__CB_Opportunity_Coupon__c 
                WHERE chargebeeapps__Opportunity__c =: q.OpportunityId
            ];
            // doubleTotalServiceSP = 0.00;
            // doubleTotalServiceDiscount = 0.00;
            // doubleSubTotalService = 0.00;
            // doubleTotalSoftwareSP = 0.00;
            // doubleTotalSoftwareDiscount = 0.00;
            // doubleSubTotalSoftware = 0.00;
            // if(q.QuoteLineItems != null && q.QuoteLineItems.size()>0){
            //     for(QuoteLineItem qli: q.QuoteLineItems){
            //         if(qli.PricebookEntry.Product2.Business_Line__c != null && qli.PricebookEntry.Product2.Business_Line__c.equalsIgnoreCase(businessLineProfessionalServices)){
            //             doubleTotalServiceSP += qli.Extended_Price__c;
            //             doubleTotalServiceDiscount += qli.Discount_price__c;
            //         }else if(qli.PricebookEntry.Product2.Business_Line__c != null && (qli.PricebookEntry.Product2.Business_Line__c == 'GP' || qli.PricebookEntry.Product2.Business_Line__c == 'BC')){
            //             doubleTotalSoftwareSP += qli.Extended_Price__c;
            //             doubleTotalSoftwareDiscount += qli.Discount_price__c;
            //         }
            //     }
            // }
            // doubleSubTotalService = doubleTotalServiceSP+doubleTotalServiceDiscount;
            // doubleSubTotalSoftware = doubleTotalSoftwareSP+doubleTotalSoftwareDiscount;
            
            totalSoftwareSP = Utility_Class.currencyStringFormatter(q.Total_Software_Sales_Price__c);
            totalSoftwareDiscount = Utility_Class.currencyStringFormatter(q.Total_Software_Discount__c);
            totalSoftwareSubtotal = Utility_Class.currencyStringFormatter(q.Total_Software_Subtotal__c);
            totalServiceSP = Utility_Class.currencyStringFormatter(q.Total_Service_Sales_Price__c);
            totalServiceDiscount = Utility_Class.currencyStringFormatter(q.Total_Service_Discount__c);
            totalServiceSubtotal = Utility_Class.currencyStringFormatter(q.Total_Service_Subtotal__c);
        }
        catch(Exception e) {
            ApexPages.addMessages(e);
        }
    }
    
    
    public PageReference saveAndOpenPDF() {
        if (String.isBlank(ApexPages.currentPage().getParameters().get('displayOnly'))) {
            Id attachmentId = savePDF();
            return openPDF(attachmentId);
        } else {
            return null;
        }
    }
    
    public PageReference saveAndOpenPDFSubtotal() {
        if (String.isBlank(ApexPages.currentPage().getParameters().get('displayOnly'))) {
            Id attachmentId = savePDFSubtotal();
            return openPDF(attachmentId);
        } else {
            return null;
        }
    }
    
    public Id savePDF() {
        Attachment attachment = new Attachment();
        attachment.ParentId = quoteId;
        Integer versionNumber = getVersionNumber()+1;
        attachment.name = 'Quote_V'+versionNumber+'.pdf';
        PageReference pdf = Page.QuotePDF;
        pdf.getParameters().put('Id', quoteId);
        pdf.getParameters().put('displayOnly', '1');
        pdf.setRedirect(true);
        try {
            attachment.Body = pdf.getContent();
        }
        catch (VisualForceException e) {
            attachment.Body = Blob.valueof('There was an error.');
        }
        attachment.ContentType = 'application/pdf';
        insert attachment;
        
        updateVersionNumber(versionNumber);
        
        return attachment.Id;
    }
    
    public Id savePDFSubtotal() {
        Attachment attachment = new Attachment();
        attachment.ParentId = quoteId;
        Integer versionNumber = getVersionNumber()+1;
        attachment.name = 'Quote_V'+versionNumber+'.pdf';
        PageReference pdf = Page.QuotePDFSubtotal;
        pdf.getParameters().put('Id', quoteId);
        pdf.getParameters().put('displayOnly', '1');
        pdf.setRedirect(true);
        try {
            attachment.Body = pdf.getContent();
        }
        catch (VisualForceException e) {
            attachment.Body = Blob.valueof('There was an error.');
        }
        attachment.ContentType = 'application/pdf';
        insert attachment;
        
        updateVersionNumber(versionNumber);
        
        return attachment.Id;
    }
    
    private void updateVersionNumber(Integer newNumber) {
        Quote updatedQuote = new Quote(Id = q.Id, Number_of_Quotes_Generated__c = newNumber);
        try {
            update updatedQuote;
        } catch(Exception e) {
            ApexPages.addMessages(e);
        }
    }
    
    private Integer getVersionNumber() {
        return q.Number_of_Quotes_Generated__c  == null ? 0 : Integer.valueOf(q.Number_of_Quotes_Generated__c);
    }
    
    public PageReference openPDF(Id attachmentId) {
        PageReference ret = new PageReference('/servlet/servlet.FileDownload?file=' + attachmentId);
        ret.setRedirect(true);
        return ret;
    }
    
    public Boolean showWaterMark {
        get{
            return waterMarkSet.contains(q.Status);
        }
    }
    
}