force-app/main/default/objects/Opportunity/fields/Opportunity_Source__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source__c</fullName>
    <label>DEPRECATE Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>SDR</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Maketing</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
                <isActive>false</isActive>
                <label>Blog</label>
            </value>
            <value>
                <fullName>Business Process Review</fullName>
                <isActive>false</isActive>
                <label>Business Process Review</label>
            </value>
            <value>
                <fullName>Cavallo Consulting</fullName>
                <isActive>false</isActive>
                <label>Cavallo Consulting</label>
            </value>
            <value>
                <fullName>Cavallo Support</fullName>
                <isActive>false</isActive>
                <label>Cavallo Support</label>
            </value>
            <value>
                <fullName>Customer RFQ</fullName>
                <isActive>false</isActive>
                <label>Customer RFQ</label>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
                <isActive>false</isActive>
                <label>Customer Referral</label>
            </value>
            <value>
                <fullName>Innovation</fullName>
                <isActive>false</isActive>
                <label>Innovation</label>
            </value>
            <value>
                <fullName>InsideView</fullName>
                <isActive>false</isActive>
                <label>InsideView</label>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
                <isActive>false</isActive>
                <label>Outbound Call</label>
            </value>
            <value>
                <fullName>PR</fullName>
                <isActive>false</isActive>
                <label>PR</label>
            </value>
            <value>
                <fullName>Paid Media</fullName>
                <isActive>false</isActive>
                <label>Paid Media</label>
            </value>
            <value>
                <fullName>Paid Search</fullName>
                <isActive>false</isActive>
                <label>Paid Search</label>
            </value>
            <value>
                <fullName>Podcast</fullName>
                <isActive>false</isActive>
                <label>Podcast</label>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <isActive>false</isActive>
                <label>Reseller</label>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
                <isActive>false</isActive>
                <label>Sales Rep</label>
            </value>
            <value>
                <fullName>Search</fullName>
                <isActive>false</isActive>
                <label>Search</label>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
                <isActive>false</isActive>
                <label>Strategic Partner</label>
            </value>
            <value>
                <fullName>Trade Publications</fullName>
                <isActive>false</isActive>
                <label>Trade Publications</label>
            </value>
            <value>
                <fullName>User Conference</fullName>
                <isActive>false</isActive>
                <label>User Conference</label>
            </value>
            <value>
                <fullName>Webinar/ Virtual Event</fullName>
                <isActive>false</isActive>
                <label>Webinar/ Virtual Event</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source_Global__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source_Global__c</fullName>
    <label>Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Subsource__c</fullName>
    <label>DEPRECATE Opportunity Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>BPR</fullName>
            </value>
            <value>
                <fullName>Cavallo Employee</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Customer Inbound Request</fullName>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Digital ads (Google, Bing)</fullName>
            </value>
            <value>
                <fullName>DUG Forums</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Event / Tradeshow</fullName>
            </value>
            <value>
                <fullName>General Prospecting</fullName>
            </value>
            <value>
                <fullName>GPUG Forums</fullName>
            </value>
            <value>
                <fullName>Independent Consultant</fullName>
            </value>
            <value>
                <fullName>Juhl</fullName>
            </value>
            <value>
                <fullName>Kayako</fullName>
            </value>
            <value>
                <fullName>Key2Act</fullName>
            </value>
            <value>
                <fullName>LinkedIn Navigator</fullName>
            </value>
            <value>
                <fullName>Marketing: User Conferences</fullName>
            </value>
            <value>
                <fullName>Microsoft AppSource</fullName>
            </value>
            <value>
                <fullName>MSDW</fullName>
            </value>
            <value>
                <fullName>Newsletter</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Email</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Paid Search</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Partner Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_SubSource_Global__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_SubSource_Global__c</fullName>
    <label>Opportunity Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Source_Global__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Subsource</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Cavallo</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA)-INS | salespadllcdbacavallosolutions1644863490847.cavallo_profit_scan</fullName>
    </customValue>
    <customValue>
        <fullName>PMP AA</fullName>
    </customValue>
    <customValue>
        <fullName>AppSource (SPZA) - INS</fullName>
        <isActive>false</isActive>
        <label>AppSource (SPZA) - INS</label>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Subsource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ABM</fullName>
    </customValue>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Applied AI for Distributors</fullName>
    </customValue>
    <customValue>
        <fullName>Blog</fullName>
    </customValue>
    <customValue>
        <fullName>BPR</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Cavallo Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Change Order</fullName>
    </customValue>
    <customValue>
        <fullName>Cliently</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Accumatica</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - acuConnect</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - AM Expo 2025</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - CSNA</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Directions EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Directions NA</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - DUG</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - GPUC</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Innovia</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Stoneridge</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Summit</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - TM Group</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - User</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - Velosio ASPIRE</fullName>
    </customValue>
    <customValue>
        <fullName>Conf - WennSoft Synergy</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Request</fullName>
    </customValue>
    <customValue>
        <fullName>Digital ads (Google, Bing)</fullName>
    </customValue>
    <customValue>
        <fullName>DSG Webinars</fullName>
    </customValue>
    <customValue>
        <fullName>DUG Forums</fullName>
    </customValue>
    <masterLabel>Lead Subsource</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RecordUpdateBatch.cls
public class RecordUpdateBatch implements Database.Batchable<sObject>{
 
    public Database.QueryLocator start(Database.BatchableContext BC){
        if(test.isrunningTest()){
            integer i=0;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;
            i++;

            return Database.getQueryLocator('Select id,Opportunity_Source__c,LeadSource,Opportunity_Source_Global__c,Opportunity_Subsource__c,Opportunity_SubSource_Global__c from Opportunity Where Opportunity_Source_Global__c =null and Opportunity_Source__c != null LIMIT 1');
            
           // return Database.getQueryLocator('Select id,Opportunity_Source_Global__c,LeadSource where Opportunity_Source_Global__c =null and LeadSource != null LIMIT 1');
            
        }
      // return Database.getQueryLocator('Select id,Opportunity_Source__c,LeadSource,Opportunity_Source_Global__c,Opportunity_Subsource__c,Opportunity_SubSource_Global__c from Opportunity Where Opportunity_Source_Global__c =null and Opportunity_Source__c != null');
   
       return Database.getQueryLocator('Select id,Opportunity_Source_Global__c,LeadSource,Opportunity_Subsource__c from Opportunity where Opportunity_Source_Global__c =null and LeadSource != null');

              
    }
  
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Opportunity> opplist = (List<Opportunity>) scope;
        for(Opportunity oppobj:opplist){
            if(oppobj.Opportunity_Subsource__c == 'Customer Request'){
               // oppobj.Opportunity_Source_Global__c = 'Professional Services';
                //oppobj.Opportunity_SubSource_Global__c = oppobj.Opportunity_Subsource__c ;
                }else {
                 //  oppobj.Opportunity_Source_Global__c = oppobj.Opportunity_Source__c;
                   oppobj.Opportunity_Source_Global__c = oppobj.LeadSource;
             //   oppobj.Opportunity_SubSource_Global__c = oppobj.Opportunity_Subsource__c ;
            
                }
            
            }
            if(!test.isrunningTest()){
                update opplist;
            }
            
            
    }
    public void finish(Database.BatchableContext BC){}
}