force-app/main/default/objects/Partner_Client_Relationship__c/Partner_Client_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner-Client Relationship</label>
    <nameField>
        <label>Partner-Client Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner-Client Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships</relationshipLabel>
    <relationshipName>Partner_Client_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/License_Sales_Last_3_Years__c.field-meta.xml
<CustomField>
    <fullName>License_Sales_Last_3_Years__c</fullName>
    <label>License Sales – Last 3 Years</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partner_Client_Relationship__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner-Client Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Client_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/Partner_Margin__c.object-meta.xml
<CustomObject>
    <label>Partner Margin</label>
    <nameField>
        <label>Partner Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins</relationshipLabel>
    <relationshipName>Partner_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Margins (Partner)</relationshipLabel>
    <relationshipName>Partner_Margins2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Margin_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Margin_Status__c</fullName>
    <defaultValue>&apos;Pipeline&apos;</defaultValue>
    <label>Partner Margin Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Billed through Partner</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Historical</fullName>
            </value>
            <value>
                <fullName>Approved for AP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin__c/fields/Partner_Margin_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Margin_Type__c</fullName>
    <label>Partner Margin Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Purchase</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/Partner_Margin_Product__c.object-meta.xml
<CustomObject>
    <label>Partner Margin Product</label>
    <nameField>
        <label>Partner Margin Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Margin Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Licensing__c.field-meta.xml
<CustomField>
    <fullName>Licensing__c</fullName>
    <label>Licensing</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Partner_Margin__c.field-meta.xml
<CustomField>
    <fullName>Partner_Margin__c</fullName>
    <label>Partner Margin</label>
    <referenceTo>Partner_Margin__c</referenceTo>
    <relationshipLabel>Partner Margin Products</relationshipLabel>
    <relationshipName>Partner_Margin_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Perpetual_Type__c.field-meta.xml
<CustomField>
    <fullName>Perpetual_Type__c</fullName>
    <label>Perpetual Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Total_Price_Original__c  /  Quantity_Original__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partner_Margin_Product__c/recordTypes/Initial.recordType-meta.xml
<RecordType>
    <fullName>Initial</fullName>
    <active>true</active>
    <label>Initial</label>
</RecordType>

force-app/main/default/classes/PartnerClientRepMarginJob.cls
global class PartnerClientRepMarginJob implements Schedulable,Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Needs to run Monthly
        Set<String> PMStatus = new Set<String>{'Approved for AP','Billed through Partner','Historical'};
        String PMType = 'Initial Purchase';
        Set<Integer> pmLast3YearSet = new Set<Integer>{System.today().year(),System.today().year()-1,System.today().year()-2};
        
        String query = 'Select ID,Name,Partner_Margin_Status__c,Partner__c,Client__c, '+
            '(Select ID,Name,Licensing__c,Perpetual_Type__c,Total_Price__c From Partner_Margin_Products__r) '+
            'From Partner_Margin__c where Partner_Margin_Status__c In:PMStatus AND Partner_Margin_Type__c =: PMType '+
            'AND CALENDAR_YEAR(CreatedDate) In: pmLast3YearSet';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Partner_Margin__c> pmList) {
        Set<Id> partnerIdSet = new Set<Id>();
        Map<String,Decimal> pmpTotalMap = new Map<String,Decimal>();
        for(Partner_Margin__c pm : pmList){
          String partnerClientKey = (String)pm.Partner__c+(String)pm.Client__c;
           partnerIdSet.add(pm.Partner__c);
            Decimal pmpTotal = 0.00;
           for(Partner_Margin_Product__c pmp: pm.Partner_Margin_Products__r){
                            if(pmp.Total_Price__c != null && (pmp.Licensing__c == 'Subscription' || pmp.Perpetual_Type__c == 'License')){
                                pmpTotal += pmp.Total_Price__c;
                            } 
                        }
            if(pmpTotalMap == null || !pmpTotalMap.containskey(partnerClientKey)){
            	pmpTotalMap.put(partnerClientKey,pmpTotal);
            }else{
               pmpTotalMap.put(partnerClientKey, pmpTotalMap.get(partnerClientKey)+pmpTotal);
            }
        } 
        
        List<Partner_Client_Relationship__c> partnerClientList = [Select ID,Name,Partner__c,Client__c,License_Sales_Last_3_Years__c From Partner_Client_Relationship__c 
                                                                 Where Partner__c In: partnerIdSet];
        
        try{
            if(partnerClientList != null && partnerClientList.size() > 0){
                for(Partner_Client_Relationship__c pcRep: partnerClientList){
                   String pcRepPartClientKey = (String)pcRep.Partner__c+(String)pcRep.Client__c;
                    if(pmpTotalMap.containsKey(pcRepPartClientKey)){
                   		pcRep.License_Sales_Last_3_Years__c = pmpTotalMap.get(pcRepPartClientKey);
                    }
                } 
                update partnerClientList;
            }
            
        }catch(Exception e) {
            System.debug(e.getMessage());
        }    
    }
    
    global void execute(SchedulableContext sc) {
        PartnerClientRepMarginJob b = new PartnerClientRepMarginJob(); 
        Database.executeBatch(b);
    }
    
    
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }
}